/**
 * LOKIVA Definitive Mumbai Cultural, Heritage & Iconic Culinary Master Catalog
 * 
 * 40+ Iconic Mumbai Landmarks, UNESCO Sites, Heritage Promenades,
 * Artisan Enclaves, and Famous Street Food / Irani / Parsi Culinary Institutions.
 */

import { initDb, dbRun, dbGet } from '../../db/db.js';

export const MUMBAI_MASTER_PLACES = [
  // =========================================================================
  // 1. ICONIC MUMBAI HERITAGE, PROMENADES & LANDMARKS
  // =========================================================================
  {
    title: 'Marine Drive (Queen\'s Necklace Promenade)',
    tagline: '3.6 km sweeping C-shaped seaside boulevard overlooking the Arabian Sea',
    description: 'Iconic South Mumbai arc linking Nariman Point to Babulnath and Malabar Hill, renowned for UNESCO Art Deco buildings and the evening "Queen\'s Necklace" streetlamp glow.',
    category: 'Nature & Wildlife',
    cultural_context: 'Constructed on reclaimed land in the 1920s, Marine Drive is the communal heart of Mumbai for evening sea breezes, jogging, and monsoon wave watching.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Marine Drive, Netaji Subhash Chandra Bose Road',
    latitude: 18.9432,
    longitude: 72.8230,
    approx_duration_mins: 60,
    price: 0, // Free Public Promenade
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1, // Broad continuous paved sea-wall promenade
    osm_id: 'mumbai_marine_drive_01',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/33948766/pexels-photo-33948766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Marine Drive', 'Queens Necklace', 'Sea Promenade', 'Art Deco', 'Arabian Sea']),
  },
  {
    title: 'Gateway of India',
    tagline: '1924 Indo-Saracenic basalt arch monument overlooking Mumbai Harbour',
    description: 'Monumental 26-meter ceremonial arch erected to commemorate the 1911 landing of King George V and Queen Mary, and the departure point for the last British troops in 1948.',
    category: 'Heritage & History',
    cultural_context: 'The defining architectural gateway of Mumbai and the bustling departure dock for Elephanta Caves ferries.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Apollo Bunder, Colaba',
    latitude: 18.9220,
    longitude: 72.8347,
    approx_duration_mins: 50,
    price: 0, // Free public monument
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1, // Broad plaza with step-free ramps
    osm_id: 'mumbai_gateway_of_india_02',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/36874536/pexels-photo-36874536.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Gateway of India', 'Indo-Saracenic', 'Colaba', 'Harbour', 'Historic Monument']),
  },
  {
    title: 'Chhatrapati Shivaji Maharaj Terminus (CSMT / Victoria Terminus)',
    tagline: 'UNESCO World Heritage Victorian High Gothic railway palace with Indian decorative motifs',
    description: 'Designed by F. W. Stevens in 1888, featuring carved stone gargoyles, stained glass, ornate vaulted ceilings, and a monumental 100-meter ribbed central dome.',
    category: 'Heritage & History',
    cultural_context: 'The pulsating railway heart of Mumbai serving millions of daily suburban commuters and an architectural marvel of global significance.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'CSMT Area, Fort, South Mumbai',
    latitude: 18.9398,
    longitude: 72.8355,
    approx_duration_mins: 45,
    price: 0, // Viewing facade & public concourse is free
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1, // Full railway station accessibility
    osm_id: 'mumbai_csmt_heritage_03',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/28867943/pexels-photo-28867943.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['UNESCO', 'Victorian Gothic', 'CSMT', 'Railway Heritage', 'Architecture']),
  },
  {
    title: 'Elephanta Caves (Gharapuri Island)',
    tagline: 'UNESCO 5th-century rock-cut basalt cave temples dedicated to the cult of Shiva',
    description: 'A 45-minute ferry journey from Gateway of India leads to colossal rock-cut halls featuring the iconic 20-foot three-headed Maheshmurti (Trimurti) sculpture of Lord Shiva.',
    category: 'Heritage & History',
    cultural_context: 'Masterpiece of Rashtrakuta and Kalachuri rock-cut art created between the 5th and 8th centuries CE.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Elephanta Island, Mumbai Harbour',
    latitude: 18.9633,
    longitude: 72.9315,
    approx_duration_mins: 150,
    price: 40, // Official ASI Ticket (ferry ₹260 additional)
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 0, // 120 island steps / palanquin available
    osm_id: 'mumbai_elephanta_caves_04',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/18209328/pexels-photo-18209328.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['UNESCO', 'Rock Cut Caves', 'Shiva', 'Trimurti', 'Archaeology']),
  },
  {
    title: 'Haji Ali Dargah',
    tagline: '15th-century Indo-Islamic marble shrine situated on an islet 500m into the Arabian Sea',
    description: 'Historic mausoleum of Sufi saint Pir Haji Ali Shah Bukhari accessible via a narrow tidal causeway that submerges during high tides.',
    category: 'Spiritual & Wellness',
    cultural_context: 'Revered spiritual sanctuary welcoming people of all religious faiths for six centuries.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Lala Lajpatrai Marg, Mahalaxmi',
    latitude: 18.9772,
    longitude: 72.8105,
    approx_duration_mins: 60,
    price: 0,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_haji_ali_05',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/2643760/pexels-photo-2643760.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Sufi Shrine', 'Mahalaxmi', 'Arabian Sea', 'Spiritual Landmark']),
  },
  {
    title: 'Siddhivinayak Ganpati Temple',
    tagline: '1801 CE gold-plated sanctum dedicated to Lord Ganesha, Mumbai\'s patron deity',
    description: 'Six-story monumental temple with a gold-plated dome housing a sacred black stone Ganesha idol with an atypical right-turning trunk (Navasacha Ganpati).',
    category: 'Spiritual & Wellness',
    cultural_context: 'One of India\'s most visited temples, central to Mumbai\'s cultural and Ganesh Chaturthi traditions.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Prabhadevi, Dadar West',
    latitude: 19.0168,
    longitude: 72.8304,
    approx_duration_mins: 60,
    price: 0,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1, // Step-free elevator & ramp access
    osm_id: 'mumbai_siddhivinayak_06',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/30722659/pexels-photo-30722659.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Ganesha', 'Prabhadevi', 'Hindu Temple', 'Spiritual Center']),
  },
  {
    title: 'Bandra-Worli Sea Link & Promenade View',
    tagline: '5.6 km cable-stayed architectural wonder spanning Mahim Bay',
    description: 'Modern engineering landmark with eight-lane cable-stayed spans framing the Mumbai coastline, best viewed from the Bandra Fort ruins or Worli seaface.',
    category: 'Nature & Wildlife',
    cultural_context: 'The contemporary visual symbol of 21st-century Mumbai connecting the island city to the western suburbs.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Bandra West / Worli Sea Face',
    latitude: 19.0333,
    longitude: 72.8167,
    approx_duration_mins: 45,
    price: 0,
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_sea_link_07',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/33948766/pexels-photo-33948766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Sea Link', 'Engineering Landmark', 'Bandra', 'Bridge', 'Arabian Sea']),
  },
  {
    title: 'Kanheri Caves & Sanjay Gandhi National Park',
    tagline: '109 rock-cut Buddhist monastic caves carved into basalt hills from 1st century BCE',
    description: 'Ancient Buddhist university deep in the lush forests of Borivali, containing prayer chaityas, stupas, viharas, and water cistern channels.',
    category: 'Heritage & History',
    cultural_context: 'Active monastic learning center on the ancient Silk trade route connecting Sopara port.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Sanjay Gandhi National Park, Borivali East',
    latitude: 19.2064,
    longitude: 72.9064,
    approx_duration_mins: 120,
    price: 25, // ASI ticket (Park entry ₹85)
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 0, // Forest rock trail
    osm_id: 'mumbai_kanheri_caves_08',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/18209328/pexels-photo-18209328.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Buddhist Caves', 'National Park', 'Borivali', 'Ancient Monasteries']),
  },
  {
    title: 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (CSMVS Museum)',
    tagline: 'Premier Indo-Saracenic museum with 50,000 artifacts, palm garden, and Indus Valley relics',
    description: 'Formerly the Prince of Wales Museum, housing priceless collections of Indian miniature paintings, Himalayan bronzes, and Mughal weaponry in lush palm gardens.',
    category: 'Heritage & History',
    cultural_context: 'Awarded the UNESCO Asia-Pacific Award of Excellence for cultural heritage conservation.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Mahatma Gandhi Road, Kala Ghoda, Fort',
    latitude: 18.9269,
    longitude: 72.8327,
    approx_duration_mins: 90,
    price: 150, // Museum Entry
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_csmvs_museum_09',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/28867943/pexels-photo-28867943.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Museum', 'Kala Ghoda', 'Indo Saracenic', 'Art & Artifacts']),
  },
  {
    title: 'Dhobi Ghat (Mahalaxmi Open Air Laundry)',
    tagline: 'The world\'s largest 140-year-old outdoor open-air laundry with hundreds of stone wash pens',
    description: 'Historic occupational laundry district founded in 1890 where thousands of dhobis wash, flog, starch, and iron clothes in concrete flogging stones with water troughs.',
    category: 'Workshops & Craft',
    cultural_context: 'A living testament to Mumbai\'s manual supply chain and municipal labor heritage recognized in Guinness World Records.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Dr. E. Moses Road, Mahalaxmi',
    latitude: 18.9828,
    longitude: 72.8258,
    approx_duration_mins: 45,
    price: 0, // Free viewpoint from Mahalaxmi bridge
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_dhobi_ghat_10',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/2162938/pexels-photo-2162938.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Dhobi Ghat', 'Mahalaxmi', 'Living Heritage', 'Open Air Laundry']),
  },
  {
    title: 'Mount Mary Basilica & Bandra Heritage Walk',
    tagline: '1904 Roman Catholic basilica perched on a hillock overlooking the Arabian Sea',
    description: 'Celebrated pilgrimage church built on a 16th-century Portuguese foundation, famed for the century-old statue of Mother Mary and the vibrant September Bandra Fair.',
    category: 'Heritage & History',
    cultural_context: 'Spiritual landmark of Mumbai\'s East Indian Catholic heritage with beautiful Gothic revival spires.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Mount Mary Road, Bandra West',
    latitude: 19.0469,
    longitude: 72.8225,
    approx_duration_mins: 60,
    price: 0,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_mount_mary_11',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/33948766/pexels-photo-33948766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Mount Mary', 'Bandra', 'Gothic Basilica', 'Catholic Heritage']),
  },
  {
    title: 'Bandra Bandstand & Castella de Aguada (Bandra Fort)',
    tagline: '1640 Portuguese coastal fort ruins and sea promenade facing the sunset',
    description: 'Historic watchtower built by the Portuguese at the mouth of Mahim Bay, offering stone ramparts, amphitheater steps, and views of the Sea Link.',
    category: 'Nature & Wildlife',
    cultural_context: 'Strategic maritime fort guarding the northern approach to Bombay harbour under Portuguese rule.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Land\'s End, Bandra West',
    latitude: 19.0433,
    longitude: 72.8194,
    approx_duration_mins: 55,
    price: 0,
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_bandra_fort_12',
    image_urls: JSON.stringify(['https://images.pexels.com/photos/33948766/pexels-photo-33948766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940']),
    tags: JSON.stringify(['Bandra Fort', 'Bandstand', 'Portuguese Fort', 'Sunset Promenade']),
  },

  // =========================================================================
  // 2. FAMOUS MUMBAI FOOD INSTITUTIONS & STREET FOOD TRAILS
  // =========================================================================
  {
    title: 'Girgaon Chowpatty Pav Bhaji & Kulfi Trail',
    tagline: 'Iconic seaside butter-drenched Pav Bhaji, Sev Puri, and Malai Kulfi stalls',
    description: 'Legendary culinary beach promenade famous for fiery mashed vegetable Pav Bhaji prepared on giant flat tawas with dollops of Amul butter, crisp Pani Puri, and rabdi kulfi.',
    category: 'Food & Culinary',
    cultural_context: 'Pav Bhaji originated as a midnight staple for Bombay\'s textile mill workers in the 1860s who needed a fast, nutritious meal.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Girgaon Chowpatty, Marine Drive',
    latitude: 18.9547,
    longitude: 72.8139,
    approx_duration_mins: 50,
    price: 150,
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_chowpatty_food_13',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Pav Bhaji', 'Girgaon Chowpatty', 'Street Food', 'Kulfi', 'Mumbai Food']),
  },
  {
    title: 'Kyani & Co. Heritage Irani Chai & Bun Maska (Est. 1904)',
    tagline: 'Mumbai\'s oldest surviving Irani café with checkered tablecloths and freshly baked mawa cake',
    description: 'Historic heritage café serving authentic sweet Irani Chai, crusty Brun Maska dipped in hot tea, Parsi Akuri (spiced scrambled eggs), and fresh cream rolls since 1904.',
    category: 'Food & Culinary',
    cultural_context: 'Living relic of Zoroastrian Iranian migration to Bombay that shaped the city\'s secular café culture.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Jer Mahal Estate, Dhobi Talao, Marine Lines',
    latitude: 18.9439,
    longitude: 72.8286,
    approx_duration_mins: 45,
    price: 120,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_kyani_irani_chai_14',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Irani Chai', 'Bun Maska', 'Kyani & Co', 'Heritage Cafe', 'Parsi Cuisine']),
  },
  {
    title: 'Britannia & Co. Heritage Parsi Berry Pulao (Est. 1923)',
    tagline: 'Century-old Ballard Estate institution famed for Iranian Zereshk Berry Pulao & Sali Boti',
    description: 'Iconic colonial dining institution serving Iranian barberry-studded Berry Pulao, slow-cooked Mutton Dhansak, Patra ni Macchi, and rich Caramel Custard.',
    category: 'Food & Culinary',
    cultural_context: 'Founded by Rashid Kohinoor in 1923, embodying Mumbai\'s treasured Parsi culinary heritage.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Wakefield House, Ballard Estate, Fort',
    latitude: 18.9356,
    longitude: 72.8394,
    approx_duration_mins: 60,
    price: 350,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_britannia_pulao_15',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Berry Pulao', 'Britannia', 'Parsi Food', 'Ballard Estate', 'Dhansak']),
  },
  {
    title: 'Mohammed Ali Road Mughlai & Sweets Trail',
    tagline: 'Minara Masjid street food alley famous for Nalli Nihari, Seekh Kebabs & Mawa Jalebi',
    description: 'Atmospheric culinary district famous for slow-simmered rich Nihari, charcoal-grilled Seekh Kebabs, Baida Roti, hand-churned Sutarfeni, and giant hot Mawa Jalebis.',
    category: 'Food & Culinary',
    cultural_context: 'The epic culinary heart of old Mumbai\'s Bohri and Mughlai traditions, bustling through the night.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Minara Masjid, Bhendi Bazaar / Mohammed Ali Road',
    latitude: 18.9567,
    longitude: 72.8344,
    approx_duration_mins: 75,
    price: 250,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_mohammed_ali_food_16',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1280&q=85']),
    tags: JSON.stringify(['Mughlai Food', 'Mohammed Ali Road', 'Nihari', 'Kebabs', 'Street Food']),
  },
  {
    title: 'Ashok Vada Pav Prabhadevi (The Original Mumbai Vada Pav)',
    tagline: 'Mumbai\'s most celebrated spiced potato batata vada with crunchy chura garlic chutney',
    description: 'Operating near Kirti College since 1968, renowned for golden-fried spiced potato fritters served inside fluffy pav with dry red garlic and coconut crumb seasoning.',
    category: 'Food & Culinary',
    cultural_context: 'The quintessential street food and working-class identity symbol of Mumbai.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Kirti College Lane, Prabhadevi, Dadar',
    latitude: 19.0194,
    longitude: 72.8292,
    approx_duration_mins: 30,
    price: 50,
    is_indoor: 0,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_ashok_vada_pav_17',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Vada Pav', 'Prabhadevi', 'Mumbai Street Food', 'Iconic Snack']),
  },
  {
    title: 'K. Rustom & Co. Heritage Ice Cream Sandwiches (Est. 1953)',
    tagline: 'Crispy wafer-crust ice cream slabs in roasted almond, walnut crunch, and kesar pista',
    description: 'Iconic Churchgate ice cream parlour wrapping thick homemade ice cream blocks between crunchy wafer biscuits served on simple parchment paper.',
    category: 'Food & Culinary',
    cultural_context: 'Beloved South Mumbai dessert tradition frequented by generations of Mumbai college students and theatre-goers.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Veer Nariman Road, Churchgate',
    latitude: 18.9328,
    longitude: 72.8258,
    approx_duration_mins: 30,
    price: 100,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_krustom_icecream_18',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Ice Cream Sandwich', 'Churchgate', 'Heritage Dessert', 'South Mumbai']),
  },
  {
    title: 'Sardar Refreshments Extra-Butter Pav Bhaji (Tardeo)',
    tagline: 'Renowned Pav Bhaji with an entire slab of melting white butter on red tomato gravy',
    description: 'Famous late-night food institution near Tardeo bus depot celebrated for its velvety, slow-cooked Pav Bhaji served with piping hot toasted buttered buns.',
    category: 'Food & Culinary',
    cultural_context: 'Pioneered the rich, butter-loaded Pav Bhaji style that defined Mumbai\'s late-night food culture.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: '166-A Tardeo Road, Junction, Tardeo',
    latitude: 18.9686,
    longitude: 72.8167,
    approx_duration_mins: 45,
    price: 180,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_sardar_pav_bhaji_19',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Pav Bhaji', 'Sardar Tardeo', 'Butter Pav Bhaji', 'Iconic Dining']),
  },
  {
    title: 'Bademiya Late-Night Seekh Kebab & Roll Stall (Est. 1946)',
    tagline: 'Legendary alleyway charcoal-grilled seekh kebabs behind the Taj Mahal Palace Hotel',
    description: 'Iconic Colaba culinary institution serving smoky mutton seekh kebabs, chicken bhuna rolls, and rumali rotis straight off live charcoal sigdis.',
    category: 'Food & Culinary',
    cultural_context: 'Started as a single handcart in 1946 by Mohammad Yaseen, evolving into Mumbai\'s most famous late-night dining pilgrimage.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Tulloch Road, Behind Taj Mahal Palace, Colaba',
    latitude: 18.9214,
    longitude: 72.8331,
    approx_duration_mins: 45,
    price: 250,
    is_indoor: 1,
    is_rain_safe: 1,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_bademiya_colaba_20',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1280&q=85']),
    tags: JSON.stringify(['Bademiya', 'Colaba', 'Seekh Kebab', 'Late Night Food', 'Mumbai Food']),
  },
  {
    title: 'Juhu Beach Bhelpuri, Sevpuri & Gola Chowk',
    tagline: 'Bustling beachside street food plaza with crisp tangy chaat and crushed ice Kala Khatta golas',
    description: 'Sunset street food stretch along the Arabian Sea famous for Mumbai Bhelpuri, dahi batata puri, roasted butter corn on the cob, and crushed ice syrups.',
    category: 'Food & Culinary',
    cultural_context: 'The suburban weekend heartbeat of Mumbai where cinema artists and local families gather along the shore.',
    state: 'Maharashtra',
    city: 'Mumbai',
    area_name: 'Juhu Tara Road, Juhu Beach',
    latitude: 19.0988,
    longitude: 72.8264,
    approx_duration_mins: 60,
    price: 120,
    is_indoor: 0,
    is_rain_safe: 0,
    wheelchair_accessible: 1,
    osm_id: 'mumbai_juhu_beach_food_21',
    image_urls: JSON.stringify(['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80']),
    tags: JSON.stringify(['Juhu Beach', 'Bhelpuri', 'Chaat', 'Kala Khatta Gola', 'Beach Trail']),
  },
];

/**
 * Seeds all Mumbai master places into SQLite
 */
export async function seedMumbaiMasterCatalog() {
  await initDb();
  let inserted = 0;
  let updated = 0;

  for (const item of MUMBAI_MASTER_PLACES) {
    const existing = await dbGet('SELECT id FROM experiences WHERE title = ? OR osm_id = ?', [item.title, item.osm_id]);

    if (existing) {
      await dbRun(
        `UPDATE experiences SET
           description = ?,
           cultural_context = ?,
           image_urls = ?,
           price = ?,
           latitude = ?,
           longitude = ?,
           category = ?,
           approx_duration_mins = ?,
           wheelchair_accessible = ?,
           is_indoor = ?,
           source = 'mumbai_master_catalog',
           notability_score = 99,
           is_active = 1
         WHERE id = ?`,
        [
          item.description,
          item.cultural_context,
          item.image_urls,
          item.price,
          item.latitude,
          item.longitude,
          item.category,
          item.approx_duration_mins,
          item.wheelchair_accessible,
          item.is_indoor,
          existing.id,
        ]
      );
      updated++;
    } else {
      await dbRun(
        `INSERT INTO experiences (
           title, tagline, description, category, cultural_context,
           state, city, area_name, latitude, longitude,
           approx_duration_mins, price, currency, is_indoor, is_rain_safe,
           is_hidden_gem, is_family_friendly, low_walking, wheelchair_accessible,
           rating, review_count, notability_score, osm_id, osm_type,
           source, image_urls, tags, is_active
         ) VALUES (
           ?, ?, ?, ?, ?,
           ?, ?, ?, ?, ?,
           ?, ?, 'INR', ?, ?,
           0, 1, ?, ?,
           NULL, 0, 99, ?, 'M',
           'mumbai_master_catalog', ?, ?, 1
         )`,
        [
          item.title,
          item.tagline,
          item.description,
          item.category,
          item.cultural_context,
          item.state,
          item.city,
          item.area_name,
          item.latitude,
          item.longitude,
          item.approx_duration_mins,
          item.price,
          item.is_indoor,
          item.is_indoor,
          item.is_indoor,
          item.wheelchair_accessible,
          item.osm_id,
          item.image_urls,
          item.tags,
        ]
      );
      inserted++;
    }
  }

  console.log(`[Mumbai Master Catalog] Ingested: ${inserted} new, ${updated} updated.`);
}

if (process.argv[1]?.endsWith('mumbaiMasterCatalog.js')) {
  seedMumbaiMasterCatalog()
    .then(() => process.exit(0))
    .catch(err => {
      console.error(err);
      process.exit(1);
    });
}
