/**
 * LOKIVA Pan-India Master Cultural & Destination Dataset
 * 
 * Complete coverage of:
 * - All 28 Indian States & 8 Union Territories (36 Entities)
 * - Tier 1, Tier 2, Tier 3 Cities, Artisan Clusters, GI-tag Craft Guilds,
 *   Heritage Sites, Hill Stations, Coastal Enclaves, and Hidden Cultural Jewels.
 * - Robust Aliases for seamless search (e.g. Chhatrapati Sambhajinagar <-> Aurangabad,
 *   Bengaluru <-> Bangalore, Prayagraj <-> Allahabad, Varanasi <-> Kashi / Benares).
 */

import { dbRun, dbGet, dbAll } from '../../db/db.js';

export const PAN_INDIA_STATES_DATASET = [
  // ================= 28 STATES =================
  {
    name: 'Andhra Pradesh',
    code: 'AP',
    region: 'South India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    description: 'Coromandel coastline, sacred hill temples of Tirumala, Araku coffee valleys, and Kalamkari textile traditions of Machilipatnam.',
    heritage_count: 24,
  },
  {
    name: 'Arunachal Pradesh',
    code: 'AR',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=800&q=80',
    description: 'Land of Dawn-Lit Mountains, ancient Tawang Buddhist Monastery, Ziro Valley Apatani pine forests, and tribal weaving heritage.',
    heritage_count: 14,
  },
  {
    name: 'Assam',
    code: 'AS',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80',
    description: 'Brahmaputra riverine heritage, golden Muga silk weaving in Sualkuchi, UNESCO Kaziranga grasslands, and Majuli neo-Vaishnavite sattras.',
    heritage_count: 22,
  },
  {
    name: 'Bihar',
    code: 'BR',
    region: 'East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
    description: 'Cradle of ancient learning at Nalanda University, sacred Mahabodhi Temple at Bodh Gaya, and intricate Madhubani folk painting traditions.',
    heritage_count: 29,
  },
  {
    name: 'Chhattisgarh',
    code: 'CG',
    region: 'Central India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1626014303757-64663673fdf8?auto=format&fit=crop&w=800&q=80',
    description: 'Bastar tribal bell-metal Dhokra casting, Chitrakote horseshoe falls, 7th-century brick temples of Sirpur, and sacred Sal forests.',
    heritage_count: 18,
  },
  {
    name: 'Goa',
    code: 'GA',
    region: 'West India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    description: 'Latin quarters of Fontainhas, Baroque Portuguese churches, Mario Miranda art studios, spice plantation trails, and Konkan coastal cuisine.',
    heritage_count: 21,
  },
  {
    name: 'Gujarat',
    code: 'GJ',
    region: 'West India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    description: 'White desert of Kutch, double-ikat Patola silk weaving of Patan, Stepwells of Adalaj, and the heritage pols of UNESCO Ahmedabad.',
    heritage_count: 36,
  },
  {
    name: 'Haryana',
    code: 'HR',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    description: 'Historic battlefields of Kurukshetra and Panipat, Mughal-styled Yadavindra Gardens of Pinjore, and Surajkund international crafts heritage.',
    heritage_count: 15,
  },
  {
    name: 'Himachal Pradesh',
    code: 'HP',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    description: 'Spiti high-altitude Tibetan Buddhist gompas, Kangra miniature painting ateliers, Chamba double-sided embroidery, and cedar-lined valleys.',
    heritage_count: 26,
  },
  {
    name: 'Jharkhand',
    code: 'JH',
    region: 'East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    description: 'Sohrai and Khovar indigenous mural art, sacred Jyotirlinga shrine of Baidyanath Deoghar, Betla forests, and Hundru waterfalls.',
    heritage_count: 16,
  },
  {
    name: 'Karnataka',
    code: 'KA',
    region: 'South India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1600100397608-f010f444f434?auto=format&fit=crop&w=800&q=80',
    description: 'Boulder-strewn Vijayanagara ruins of Hampi, Hoysala star-shaped temples of Belur-Halebidu, Channapatna toy craft, and Coorg coffee estates.',
    heritage_count: 42,
  },
  {
    name: 'Kerala',
    code: 'KL',
    region: 'South India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    description: 'Kathakali and Theyyam ritual performances, tranquil Vembanad backwaters, spice-trading Jew Town in Fort Kochi, and Wayanad rainforests.',
    heritage_count: 34,
  },
  {
    name: 'Madhya Pradesh',
    code: 'MP',
    region: 'Central India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    description: 'Erotic stone carvings of UNESCO Khajuraho, Sanchi Buddhist Stupa, medieval cenotaphs of Orchha, and royal palaces of Gwalior and Mandu.',
    heritage_count: 48,
  },
  {
    name: 'Maharashtra',
    code: 'MH',
    region: 'West India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    description: 'Ajanta & Ellora rock-cut caves, Maratha sea & hill fortresses, Art Deco Mumbai architecture, Warli tribal art, and Konkan coastal culture.',
    heritage_count: 52,
  },
  {
    name: 'Manipur',
    code: 'MN',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1596405835955-463df1c3df5e?auto=format&fit=crop&w=800&q=80',
    description: 'Floating phumdis of Loktak Lake, martial Thang-Ta traditions, classic Manipuri Raas Leela dance, and Longpi black stone pottery.',
    heritage_count: 13,
  },
  {
    name: 'Meghalaya',
    code: 'ML',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    description: 'Bio-engineered Living Root Bridges of Cherrapunji, crystal waters of Umngot in Dawki, sacred Khasi groves, and cave systems of Jaintia.',
    heritage_count: 19,
  },
  {
    name: 'Mizoram',
    code: 'MZ',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1616885375498-500b58e77a11?auto=format&fit=crop&w=800&q=80',
    description: 'Cheraw bamboo dance rhythms, verdant rolling hills of Aizawl and Reiek, handloom Puan weaving, and warm Mizo community homestays.',
    heritage_count: 11,
  },
  {
    name: 'Nagaland',
    code: 'NL',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    description: 'Hornbill cultural celebrations, warrior woodcarving guilds of Mon and Konyak clans, green terraced hills of Khonoma eco-village.',
    heritage_count: 15,
  },
  {
    name: 'Odisha',
    code: 'OD',
    region: 'East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1609137144822-2630b427493a?auto=format&fit=crop&w=800&q=80',
    description: 'Sun Temple chariot of Konark, holy Jagannath Rath Yatra in Puri, Pattachitra scroll painting artists in Raghurajpur, and Chilika lagoon.',
    heritage_count: 38,
  },
  {
    name: 'Punjab',
    code: 'PB',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    description: 'The Golden Temple (Sri Harmandir Sahib) of Amritsar, grand community langar kitchens, vibrant Phulkari textile embroidery, and dhaba cuisine.',
    heritage_count: 23,
  },
  {
    name: 'Rajasthan',
    code: 'RJ',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    description: 'Pink sandstone palaces of Jaipur, Blue City alleys of Jodhpur, Golden Desert fort of Jaisalmer, Lake Palace Udaipur, and Bagru block prints.',
    heritage_count: 65,
  },
  {
    name: 'Sikkim',
    code: 'SK',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
    description: 'Views of Mt. Kanchenjunga, Rumtek and Pemayangtse Tibetan monasteries, Gurudongmar alpine lake, and organic cardamom tea plantations.',
    heritage_count: 17,
  },
  {
    name: 'Tamil Nadu',
    code: 'TN',
    region: 'South India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    description: 'Dravidian gopuram architecture of Madurai and Thanjavur, shore temples of Mahabalipuram, Kanchipuram silk weavers, and Chettinad mansions.',
    heritage_count: 58,
  },
  {
    name: 'Telangana',
    code: 'TG',
    region: 'South India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=800&q=80',
    description: 'Monumental Charminar and Golconda fortress of Hyderabad, Kakatiya floating stone temple of Ramappa, and Pochampally Ikkat silk weaves.',
    heritage_count: 27,
  },
  {
    name: 'Tripura',
    code: 'TR',
    region: 'North-East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    description: 'Enigmatic rock-cut Shaivite reliefs of Unakoti, white domed Ujjayanta and Neermahal water palaces, and exquisite bamboo cane craftsmanship.',
    heritage_count: 12,
  },
  {
    name: 'Uttar Pradesh',
    code: 'UP',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    description: 'Eternal ghats and Ganga Aarti of Varanasi, the marble Taj Mahal of Agra, Nawabi Awadhi culinary trails in Lucknow, and sacred Ayodhya.',
    heritage_count: 62,
  },
  {
    name: 'Uttarakhand',
    code: 'UK',
    region: 'North India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    description: 'Yoga capital and Ganga ashrams of Rishikesh, Himalayan sacred Char Dham shrines, Kumaoni Aipan art in Almora, and alpine meadows of Auli.',
    heritage_count: 31,
  },
  {
    name: 'West Bengal',
    code: 'WB',
    region: 'East India',
    is_union_territory: 0,
    image_url: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80',
    description: 'Colonial heritage and coffee house debates in Kolkata, terracotta temples of Bishnupur, Tagore\'s Shantiniketan, and Darjeeling tea estates.',
    heritage_count: 45,
  },

  // ================= 8 UNION TERRITORIES =================
  {
    name: 'Andaman and Nicobar Islands',
    code: 'AN',
    region: 'Islands',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    description: 'Historic Cellular Jail in Port Blair, turquoise coral lagoons of Havelock (Swaraj Dweep), limestone caves of Baratang, and tribal reserves.',
    heritage_count: 14,
  },
  {
    name: 'Chandigarh',
    code: 'CH',
    region: 'North India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    description: 'Le Corbusier\'s UNESCO Capitol Complex modernist architecture, Nek Chand\'s whimsical Rock Garden, and tranquil Sukhna Lake promenade.',
    heritage_count: 10,
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DNHDD',
    region: 'West India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    description: 'Portuguese sea fortresses of Moti Daman and Diu Island, St. Paul\'s Church, Warli tribal craft centers of Silvassa, and palm-fringed coastlines.',
    heritage_count: 11,
  },
  {
    name: 'Delhi',
    code: 'DL',
    region: 'North India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    description: 'Seven historic capitals spanning Qutub Minar, Humayun\'s Tomb, Old Delhi Mughal food lanes of Chandni Chowk, and vibrant artisanal Dilli Haat.',
    heritage_count: 55,
  },
  {
    name: 'Jammu and Kashmir',
    code: 'JK',
    region: 'North India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=80',
    description: 'Dal Lake shikaras and Mughal gardens in Srinagar, GI-tagged Pashmina & walnut woodcraft, meadow alpine trails in Gulmarg and Pahalgam.',
    heritage_count: 28,
  },
  {
    name: 'Ladakh',
    code: 'LA',
    region: 'North India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=800&q=80',
    description: 'High-altitude desert monastic citadel of Leh, Thiksey Gompa chants, sand dunes of Nubra Valley, Pangong Tso azure waters, and Aryan valley traditions.',
    heritage_count: 25,
  },
  {
    name: 'Lakshadweep',
    code: 'LD',
    region: 'Islands',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    description: 'Pristine coral atolls of Bangaram, Agatti, and Kavaratti, coir rope handicraft cooperatives, traditional boat making, and marine biodiversity.',
    heritage_count: 8,
  },
  {
    name: 'Puducherry',
    code: 'PY',
    region: 'South India',
    is_union_territory: 1,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    description: 'French colonial White Town promenade, Tamil quarters of Heritage Town, spiritual community of Auroville, handmade paper mills, and seaside bakeries.',
    heritage_count: 18,
  },
];

export const PAN_INDIA_CITIES_DATASET = [
  // ================= MAHARASHTRA =================
  {
    name: 'Mumbai',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'The City of Dreams & Coastal Alleys',
    description: 'India\'s financial and creative nerve center, home to UNESCO Victorian Gothic ensembles, Sassoon Dock fishing heritage, and Irani cafe culture.',
    latitude: 19.0760,
    longitude: 72.8777,
    image_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Vibrant juxtaposition of Koli fishing villages, Bollywood studios, Parsi bakeries, and street food corridors.',
    best_time_to_visit: 'October to March',
    aliases: ['Bombay', 'Maximum City'],
    categories: ['Heritage', 'Local Food', 'Art & Culture', 'Nightlife', 'Workshops'],
    heritage_count: 18,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Pune',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'Cultural & Academic Heart of the Marathas',
    description: 'Historic seat of the Peshwas, Shaniwar Wada, classical music sabhas, and vibrant contemporary cafe culture.',
    latitude: 18.5204,
    longitude: 73.8567,
    image_url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Maratha history, Puneri Misal food trails, Osho ashram tranquility, and IT innovations.',
    best_time_to_visit: 'July to February',
    aliases: ['Poona', 'Oxford of the East'],
    categories: ['Heritage', 'Local Food', 'Workshops', 'Art & Culture'],
    heritage_count: 14,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Chhatrapati Sambhajinagar',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'City of Gates & Rock-Cut UNESCO Masterpieces',
    description: 'Gateway to the world-renowned Ajanta & Ellora caves, Bibi Ka Maqbara, Daulatabad Fort, and Himroo silk weaving.',
    latitude: 19.8762,
    longitude: 75.3433,
    image_url: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Deccan Sultanate and Mughal architectural synthesis with Buddhist rock-cut monasteries.',
    best_time_to_visit: 'October to March',
    aliases: ['Aurangabad'],
    categories: ['Heritage', 'Art & Culture', 'Spiritual', 'Workshops'],
    heritage_count: 22,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Nashik',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'Wine Capital & Sacred Godavari Ghats',
    description: 'Kumbh Mela sacred destination, Pandavleni Buddhist caves, ancient Panchavati temples, and sprawling boutique vineyards.',
    latitude: 19.9975,
    longitude: 73.7898,
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Spiritual serenity along the Godavari river harmonized with modern agro-tourism and viticulture.',
    best_time_to_visit: 'October to March',
    aliases: ['Nasik'],
    categories: ['Spiritual', 'Local Food', 'Nature', 'Heritage'],
    heritage_count: 12,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Kolhapur',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'City of Palaces, Wrestling & GI Chappals',
    description: 'Royal seat of Chhatrapati Shahu Maharaj, Mahalakshmi Temple, authentic fiery Kolhapuri cuisine, and leather craft.',
    latitude: 16.7050,
    longitude: 74.2433,
    image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Maratha martial arts (Talim wrestling), artisanal footwear, and spicy Tambada-Pandhara Rassa feasts.',
    best_time_to_visit: 'November to February',
    aliases: ['Karveer'],
    categories: ['Heritage', 'Local Food', 'Workshops', 'Spiritual'],
    heritage_count: 10,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Nagpur',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'The Orange City & Tiger Capital of India',
    description: 'Zero Milestone geographic centre of India, Deekshabhoomi stupa, Saoji spicy culinary trails, and gateway to Tadoba wildlife.',
    latitude: 21.1458,
    longitude: 79.0882,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Vidarbha cultural heritage, Buddhist historical monuments, and rich citrus fruit orchards.',
    best_time_to_visit: 'October to March',
    aliases: ['Orange City'],
    categories: ['Nature', 'Heritage', 'Local Food', 'Spiritual'],
    heritage_count: 9,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 2'
  },
  {
    name: 'Lonavala',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'Sahyadri Cloud Forest & Buddhist Caves',
    description: 'Hill haven famed for Karla & Bhaja ancient rock-cut Buddhist chaityas, Lohagad fort trek, and handmade chikki sweets.',
    latitude: 18.7557,
    longitude: 73.4091,
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Monsoon mist, cliffside treks, historical rock-cut architecture, and artisanal candy guilds.',
    best_time_to_visit: 'June to February',
    aliases: ['Khandala'],
    categories: ['Nature', 'Adventure', 'Heritage', 'Family'],
    heritage_count: 8,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },
  {
    name: 'Alibag',
    state_name: 'Maharashtra',
    state_code: 'MH',
    tagline: 'Coastal Forts & Konkani Fisher Traditions',
    description: 'Kolaba sea fort reachable at low tide, serene coconut groves, Bene Israeli Jewish synagogue heritage, and fresh coastal seafood.',
    latitude: 18.6414,
    longitude: 72.8722,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Historic maritime battles, Bene Israeli heritage, and tranquil Konkan beachfront hamlets.',
    best_time_to_visit: 'October to April',
    aliases: ['Alibaug'],
    categories: ['Nature', 'Heritage', 'Local Food', 'Couple'],
    heritage_count: 7,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },

  // ================= KARNATAKA =================
  {
    name: 'Bengaluru',
    state_name: 'Karnataka',
    state_code: 'KA',
    tagline: 'Silicon Valley & Botanical Garden City',
    description: 'Dynamic cosmopolitan metropolis balancing Tipu Sultan\'s Summer Palace, Cubbon Park lung space, craft breweries, and filter coffee.',
    latitude: 12.9716,
    longitude: 77.5946,
    image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Modern tech innovation layered over Pete heritage markets, classical Carnatic music, and artisanal coffee roasters.',
    best_time_to_visit: 'Throughout the year',
    aliases: ['Bangalore', 'Garden City'],
    categories: ['Art & Culture', 'Local Food', 'Nightlife', 'Workshops', 'Heritage'],
    heritage_count: 16,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Mysuru',
    state_name: 'Karnataka',
    state_code: 'KA',
    tagline: 'Royal City of Palaces, Silk & Sandalwood',
    description: 'Illuminated Mysore Palace, Chamundi Hills, Devaraja fruit and flower market, GI Mysore Silk weavers, and Ashtanga yoga shalas.',
    latitude: 12.2958,
    longitude: 76.6394,
    image_url: 'https://images.unsplash.com/photo-1600100397608-f010f444f434?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Wodeyar royal heritage, world-famous Dasara festivities, pure sandalwood fragrances, and Mysore Pak sweet artisans.',
    best_time_to_visit: 'October to March',
    aliases: ['Mysore', 'City of Palaces'],
    categories: ['Heritage', 'Art & Culture', 'Workshops', 'Local Food'],
    heritage_count: 24,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Hampi',
    state_name: 'Karnataka',
    state_code: 'KA',
    tagline: 'Ruins of the Vijayanagara Empire',
    description: 'UNESCO World Heritage boulder landscape, Virupaksha Temple, stone musical chariot of Vijaya Vittala, and riverside coracle boat rides.',
    latitude: 15.3350,
    longitude: 76.4600,
    image_url: 'https://images.unsplash.com/photo-1600100397608-f010f444f434?auto=format&fit=crop&w=800&q=80',
    culture_summary: '14th-century imperial grandeur preserved in golden granite monoliths along the sacred Tungabhadra River.',
    best_time_to_visit: 'November to February',
    aliases: ['Vijayanagara', 'Kishkindha'],
    categories: ['Heritage', 'Spiritual', 'Photography', 'Backpacking'],
    heritage_count: 32,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },
  {
    name: 'Coorg',
    state_name: 'Karnataka',
    state_code: 'KA',
    tagline: 'Scotland of India & Kodava Warrior Enclave',
    description: 'Misty Western Ghats coffee and spice plantations, Abbey Falls, Namdroling Tibetan Golden Temple, and traditional Pandi Curry feasts.',
    latitude: 12.4244,
    longitude: 75.7382,
    image_url: 'https://images.unsplash.com/photo-1596405835955-463df1c3df5e?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Distinct martial Kodava traditions, sacred Talacauvery river source, and artisanal estate homestays.',
    best_time_to_visit: 'October to April',
    aliases: ['Madikeri', 'Kodagu'],
    categories: ['Nature', 'Local Food', 'Adventure', 'Couple'],
    heritage_count: 11,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },
  {
    name: 'Mangaluru',
    state_name: 'Karnataka',
    state_code: 'KA',
    tagline: 'Coastal Tuluva Heritage & Ghee Roast Trails',
    description: 'St. Aloysius Chapel Renaissance frescoes, Panambur beach, Kadri Manjunatha ancient bronze deities, and Coastal seafood cuisine.',
    latitude: 12.9141,
    longitude: 74.8560,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Tuluva culture, Yakshagana dance theater, and world-renowned Mangalorean spicy ghee roast gastronomy.',
    best_time_to_visit: 'October to March',
    aliases: ['Mangalore', 'Kudla'],
    categories: ['Local Food', 'Heritage', 'Nature', 'Spiritual'],
    heritage_count: 13,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= RAJASTHAN =================
  {
    name: 'Jaipur',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    tagline: 'The UNESCO Pink City of Royals & Artisans',
    description: 'Amber Fort, Hawa Mahal windswept facade, Jantar Mantar observatory, Sanganer block printing studios, and blue pottery.',
    latitude: 26.9124,
    longitude: 75.7873,
    image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Royal Rajput court crafts, kundan jewellery guilds, miniature paintings, and authentic Ghewar desserts.',
    best_time_to_visit: 'October to March',
    aliases: ['Pink City'],
    categories: ['Heritage', 'Art & Culture', 'Shopping', 'Workshops', 'Local Food'],
    heritage_count: 35,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Udaipur',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    tagline: 'City of Lakes & White Marble Palaces',
    description: 'Lake Pichola boat cruises, monumental City Palace complex, Jagdish Temple, Saheliyon-ki-Bari, and miniature Mewar painting schools.',
    latitude: 24.5854,
    longitude: 73.7125,
    image_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Romantic lakeside havelis, Mewar royal dynasty history, and puppet theater workshops.',
    best_time_to_visit: 'September to March',
    aliases: ['City of Lakes', 'Venice of the East'],
    categories: ['Heritage', 'Couple', 'Art & Culture', 'Photography'],
    heritage_count: 26,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Jodhpur',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    tagline: 'The Blue City & Impregnable Mehrangarh',
    description: 'Majestic Mehrangarh Fort towering over indigo-painted Brahmin quarters, Jaswant Thada, and fragrant spice and textile bazaars.',
    latitude: 26.2389,
    longitude: 73.0243,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Marwar martial fortitude, Rajasthani folk musicians (Langa-Manganiyar), and Mirchi Vada street snacks.',
    best_time_to_visit: 'October to March',
    aliases: ['Blue City', 'Sun City'],
    categories: ['Heritage', 'Music', 'Local Food', 'Photography'],
    heritage_count: 22,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Jaisalmer',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    tagline: 'The Golden Fort of the Thar Desert',
    description: 'UNESCO living golden sandstone fort, intricately carved Patwon Ki Haveli, camel desert safaris in Sam Sand Dunes, and Kalbelia folk dance.',
    latitude: 26.9157,
    longitude: 70.9083,
    image_url: 'https://images.unsplash.com/photo-1572445271230-a78b5944a659?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Desert trade route oasis, Jain temple filigree carvings, and starlit Thar musical campfires.',
    best_time_to_visit: 'November to February',
    aliases: ['Golden City'],
    categories: ['Heritage', 'Adventure', 'Music', 'Backpacking'],
    heritage_count: 20,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },
  {
    name: 'Pushkar',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    tagline: 'Sacred Brahma Lake & Annual Camel Fair',
    description: 'Rare 14th-century Lord Brahma Temple, 52 holy ghats surrounding sacred Pushkar Lake, rose gardens, and vibrant desert fair culture.',
    latitude: 26.4897,
    longitude: 74.5511,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Spiritual pilgrim chants blending with bohemian traveler cafes and rose water distillation ateliers.',
    best_time_to_visit: 'October to March',
    aliases: ['Tirth Raj'],
    categories: ['Spiritual', 'Festivals', 'Backpacking', 'Photography'],
    heritage_count: 15,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= TAMIL NADU =================
  {
    name: 'Chennai',
    state_name: 'Tamil Nadu',
    state_code: 'TN',
    tagline: 'Cultural Capital of South India & Carnatic Cradle',
    description: '7th-century Kapaleeshwarar temple, Marina Beach promenade, Kalakshetra classical dance academy, and UNESCO San Thome Basilica.',
    latitude: 13.0827,
    longitude: 80.2707,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'December Music Season, bronze idol casting, authentic filter coffee, and Chettinad culinary corridors.',
    best_time_to_visit: 'November to February',
    aliases: ['Madras', 'Gateway to South India'],
    categories: ['Art & Culture', 'Music', 'Heritage', 'Local Food', 'Spiritual'],
    heritage_count: 25,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Madurai',
    state_name: 'Tamil Nadu',
    state_code: 'TN',
    tagline: 'The Soul of Tamil Culture & Meenakshi Temple',
    description: 'Monumental towers of Meenakshi Amman Temple, Thirumalai Nayakkar Mahal, vibrant jasmine flower markets, and fragrant Jigarthanda.',
    latitude: 9.9252,
    longitude: 78.1198,
    image_url: 'https://images.unsplash.com/photo-1609137144822-2630b427493a?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Ancient Sangam literature capital with 2,500 years of continuous urban culture, temple processions, and night food markets.',
    best_time_to_visit: 'October to March',
    aliases: ['Thoonga Nagaram', 'Athens of the East'],
    categories: ['Heritage', 'Spiritual', 'Local Food', 'Festivals'],
    heritage_count: 28,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Mahabalipuram',
    state_name: 'Tamil Nadu',
    state_code: 'TN',
    tagline: 'UNESCO Shore Temples & Pallava Stone Art',
    description: '7th-century rock-cut monuments, Arjuna\'s Penance massive bas-relief, Five Rathas, and active traditional granite stone carving ateliers.',
    latitude: 12.6269,
    longitude: 80.1927,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Ancient maritime port of the Pallavas with seaside stone craftsmanship and international surfing schools.',
    best_time_to_visit: 'November to February',
    aliases: ['Mamallapuram'],
    categories: ['Heritage', 'Art & Culture', 'Workshops', 'Nature'],
    heritage_count: 20,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= KERALA =================
  {
    name: 'Kochi',
    state_name: 'Kerala',
    state_code: 'KL',
    tagline: 'Queen of the Arabian Sea & Spice Route Port',
    description: 'Cantilevered Chinese Fishing Nets, colonial Fort Kochi Portuguese alleys, Mattancherry Dutch Palace, and Kochi-Muziris Art Biennale.',
    latitude: 9.9312,
    longitude: 76.2673,
    image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Cosmopolitan trading history uniting Jews, Portuguese, Dutch, Arabs, and Malayalis with contemporary art spaces.',
    best_time_to_visit: 'September to March',
    aliases: ['Cochin', 'Fort Kochi', 'Ernakulam'],
    categories: ['Heritage', 'Art & Culture', 'Local Food', 'Workshops'],
    heritage_count: 21,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Alleppey',
    state_name: 'Kerala',
    state_code: 'KL',
    tagline: 'Venice of the East & Backwater Houseboats',
    description: 'Labyrinthine palm-lined canals, traditional Kettuvallam houseboats on Vembanad Lake, coir carpet weaving, and paddy fields below sea level.',
    latitude: 9.4981,
    longitude: 76.3388,
    image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Idyllic agrarian water village rhythms, Nehru Trophy snake boat races, and fresh karimeen fish curries.',
    best_time_to_visit: 'October to March',
    aliases: ['Alappuzha'],
    categories: ['Nature', 'Local Food', 'Couple', 'Festivals'],
    heritage_count: 11,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },
  {
    name: 'Munnar',
    state_name: 'Kerala',
    state_code: 'KL',
    tagline: 'Emerald Tea Estates & Nilgiri Tahr Sanctuary',
    description: 'Rolling green tea plantations, Eravikulam National Park, tea processing museum, and cool Western Ghats cloud cover.',
    latitude: 10.0889,
    longitude: 77.0595,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Colonial tea planter heritage, indigenous Kurumba traditions, and rare Neelakurinji blossoms.',
    best_time_to_visit: 'September to May',
    aliases: ['High Ranges'],
    categories: ['Nature', 'Adventure', 'Family', 'Couple'],
    heritage_count: 9,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },

  // ================= UTTAR PRADESH =================
  {
    name: 'Varanasi',
    state_name: 'Uttar Pradesh',
    state_code: 'UP',
    tagline: 'The Eternal Spiritual City on Sacred Ganga',
    description: 'Ancient river ghats, mesmerizing evening Ganga Aarti, Kashi Vishwanath temple, Sarnath Deer Park where Buddha first taught, and Banarasi silk weaving.',
    latitude: 25.3176,
    longitude: 82.9739,
    image_url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    culture_summary: '3,000-year continuous living spiritual civilization, classical Banaras Gharana music, zardozi needlework, and street food lanes.',
    best_time_to_visit: 'October to March',
    aliases: ['Kashi', 'Benares', 'Banaras'],
    categories: ['Spiritual', 'Heritage', 'Music', 'Workshops', 'Local Food'],
    heritage_count: 42,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Agra',
    state_name: 'Uttar Pradesh',
    state_code: 'UP',
    tagline: 'City of the Taj Mahal & Mughal Splendor',
    description: 'UNESCO Taj Mahal marble monument, monumental red sandstone Agra Fort, Fatehpur Sikri deserted city, and Pietra Dura marble inlay craft.',
    latitude: 27.1767,
    longitude: 78.0081,
    image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'High Mughal imperial architecture, generational marble inlay artisans, and fragrant Agra Petha confectioneries.',
    best_time_to_visit: 'October to March',
    aliases: ['Akbarabad'],
    categories: ['Heritage', 'Art & Culture', 'Workshops', 'Family'],
    heritage_count: 32,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },
  {
    name: 'Lucknow',
    state_name: 'Uttar Pradesh',
    state_code: 'UP',
    tagline: 'The City of Nawabs, Chikankari & Tehzeeb',
    description: 'Grand Bara Imambara labyrinth (Bhool Bhulaiya), Rumi Darwaza, delicate GI Chikankari hand embroidery, and world-renowned Galouti Kebabs.',
    latitude: 26.8467,
    longitude: 80.9462,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Refined Awadhi etiquette (Tehzeeb), Urdu poetry mushairas, Kathak dance gharana, and slow-cooked Dum Pukht cuisine.',
    best_time_to_visit: 'October to March',
    aliases: ['City of Nawabs'],
    categories: ['Heritage', 'Local Food', 'Art & Culture', 'Workshops'],
    heritage_count: 24,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= WEST BENGAL =================
  {
    name: 'Kolkata',
    state_name: 'West Bengal',
    state_code: 'WB',
    tagline: 'City of Joy, Cultural Renaissance & Adda',
    description: 'Victoria Memorial, iconic Howrah Bridge, Kumartuli idol-maker clay studios, College Street book alley, and authentic Bengali mishti feasts.',
    latitude: 22.5726,
    longitude: 88.3639,
    image_url: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Intellectual coffee house adda, UNESCO Durga Puja festivities, Rabindrasangeet, and colonial tramways.',
    best_time_to_visit: 'October to March',
    aliases: ['Calcutta', 'City of Joy'],
    categories: ['Heritage', 'Art & Culture', 'Local Food', 'Festivals', 'Workshops'],
    heritage_count: 36,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Darjeeling',
    state_name: 'West Bengal',
    state_code: 'WB',
    tagline: 'Champagne of Teas & Himalayan Toy Train',
    description: 'UNESCO Himalayan Toy Train railway, Tiger Hill sunrise over Mt. Kanchenjunga, certified biodynamic tea estates, and Tibetan monasteries.',
    latitude: 27.0410,
    longitude: 88.2663,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Victorian colonial hill architecture, Tibetan refugee craft centers, and aromatic first-flush tea tasting.',
    best_time_to_visit: 'March to May, September to November',
    aliases: ['Queen of the Hills'],
    categories: ['Nature', 'Heritage', 'Local Food', 'Adventure'],
    heritage_count: 14,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= GUJARAT =================
  {
    name: 'Ahmedabad',
    state_name: 'Gujarat',
    state_code: 'GJ',
    tagline: 'India\'s First UNESCO World Heritage City',
    description: 'Historic residential pols, Sabarmati Ashram of Mahatma Gandhi, ornate Sidi Saiyyed Jali stone lattices, and night street food market at Manek Chowk.',
    latitude: 23.0225,
    longitude: 72.5714,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Deep-rooted Jain and mercantile traditions, Calico Museum of Textiles, and colorful Navratri Garba celebrations.',
    best_time_to_visit: 'October to March',
    aliases: ['Amdavad', 'Karnavati'],
    categories: ['Heritage', 'Art & Culture', 'Local Food', 'Workshops', 'Festivals'],
    heritage_count: 30,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },
  {
    name: 'Bhuj',
    state_name: 'Gujarat',
    state_code: 'GJ',
    tagline: 'Gateway to the Great Rann of Kutch & Artisan Villages',
    description: 'Aina Mahal palace of mirrors, Prag Mahal, and artisan hamlets specializing in Rogan art, Ajrakh block printing, and Kutchi mirror embroidery.',
    latitude: 23.2420,
    longitude: 69.6669,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Desert community resilience, nomadic Rabari textiles, and white desert Rann Utsav celebrations.',
    best_time_to_visit: 'November to February',
    aliases: ['Kutch'],
    categories: ['Art & Culture', 'Workshops', 'Heritage', 'Festivals'],
    heritage_count: 18,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= TELANGANA =================
  {
    name: 'Hyderabad',
    state_name: 'Telangana',
    state_code: 'TG',
    tagline: 'City of Pearls, Nizam Palaces & Royal Biryani',
    description: 'Charminar 16th-century triumphal arch, Golconda whispering acoustic fortress, Chowmahalla Palace, and UNESCO Ramappa temple nearby.',
    latitude: 17.3850,
    longitude: 78.4867,
    image_url: 'https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Hyderabadi Deccani culture, fragrant Dum Biryani with Haleem, and Bidri silver-inlay metal craft.',
    best_time_to_visit: 'October to March',
    aliases: ['City of Pearls', 'Bhagyanagar'],
    categories: ['Heritage', 'Local Food', 'Art & Culture', 'Shopping'],
    heritage_count: 26,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },

  // ================= PUNJAB =================
  {
    name: 'Amritsar',
    state_name: 'Punjab',
    state_code: 'PB',
    tagline: 'Spiritual Sanctuary & The Golden Temple',
    description: 'The Golden Temple (Sri Harmandir Sahib), world\'s largest community mega-kitchen (Langar), Wagah Border ceremony, and Jallianwala Bagh memorial.',
    latitude: 31.6340,
    longitude: 74.8723,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Sikh hospitality, Phulkari embroidery, and legendary culinary heritage featuring buttery Kulchas and creamy Lassi.',
    best_time_to_visit: 'October to March',
    aliases: ['Ambarsar', 'Golden City of Punjab'],
    categories: ['Spiritual', 'Heritage', 'Local Food', 'Family'],
    heritage_count: 22,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= HIMACHAL PRADESH =================
  {
    name: 'Dharamshala & McLeod Ganj',
    state_name: 'Himachal Pradesh',
    state_code: 'HP',
    tagline: 'Little Lhasa & Seat of the Dalai Lama',
    description: 'Tsuglagkhang Buddhist temple complex, Norbulingka Tibetan institute of arts, Bhagsu waterfall, and pine-clad Dhauladhar mountain treks.',
    latitude: 32.2190,
    longitude: 76.3234,
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Tibetan Buddhism, Thangka painting studios, meditation retreats, and mountain cafe culture.',
    best_time_to_visit: 'March to June, September to December',
    aliases: ['McLeodganj', 'Little Lhasa'],
    categories: ['Spiritual', 'Art & Culture', 'Nature', 'Adventure'],
    heritage_count: 16,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },
  {
    name: 'Shimla',
    state_name: 'Himachal Pradesh',
    state_code: 'HP',
    tagline: 'Former British Summer Capital & Ridge Promenade',
    description: 'Gothic Christ Church, pedestrianized Mall Road and Ridge, Viceregal Lodge, and Kalka-Shimla UNESCO toy train.',
    latitude: 31.1048,
    longitude: 77.1734,
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Colonial heritage blended with Himachali wooden crafts and snow-dusted cedar forests.',
    best_time_to_visit: 'October to June',
    aliases: ['Simla'],
    categories: ['Heritage', 'Nature', 'Family', 'Couple'],
    heritage_count: 15,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= UTTARAKHAND =================
  {
    name: 'Rishikesh',
    state_name: 'Uttarakhand',
    state_code: 'UK',
    tagline: 'Yoga Capital of the World & Himalayan Ganga Gateway',
    description: 'Ganga river ashrams, Parmarth Niketan evening Aarti, Laxman Jhula, Beatles Ashram murals, and white-water river rafting.',
    latitude: 30.0869,
    longitude: 78.2676,
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Vedic philosophy, yoga & meditation immersions, Ayurvedic healing, and Himalayan adventure sports.',
    best_time_to_visit: 'September to May',
    aliases: ['Yoga Capital'],
    categories: ['Spiritual', 'Adventure', 'Nature', 'Workshops'],
    heritage_count: 19,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= ODISHA =================
  {
    name: 'Bhubaneswar & Puri',
    state_name: 'Odisha',
    state_code: 'OD',
    tagline: 'Temple City of Kalinga & Sacred Puri Coast',
    description: '11th-century Lingaraj Temple, UNESCO Konark Sun Temple chariot, Jagannath holy shrine, and Raghurajpur master Pattachitra painters.',
    latitude: 20.2961,
    longitude: 85.8245,
    image_url: 'https://images.unsplash.com/photo-1609137144822-2630b427493a?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Kalinga rock architecture, Odissi classical dance, palm-leaf engraving, and temple Mahaprasad feasts.',
    best_time_to_visit: 'October to March',
    aliases: ['Puri', 'Konark', 'Bhubaneshwar'],
    categories: ['Heritage', 'Spiritual', 'Art & Culture', 'Workshops'],
    heritage_count: 32,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= MADHYA PRADESH =================
  {
    name: 'Khajuraho & Orchha',
    state_name: 'Madhya Pradesh',
    state_code: 'MP',
    tagline: 'UNESCO Temple Sculptures & Medieval Bundelkhand Palaces',
    description: 'Intricately carved sandstone temples of Khajuraho celebrating classical Indian aesthetic sensuality, and Orchha\'s riverside cenotaphs on the Betwa.',
    latitude: 24.8318,
    longitude: 79.9199,
    image_url: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Chandela dynasty architectural brilliance and Bundela Rajput painted palace murals.',
    best_time_to_visit: 'October to March',
    aliases: ['Orchha', 'Khajuraho'],
    categories: ['Heritage', 'Art & Culture', 'Photography', 'Spiritual'],
    heritage_count: 28,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },
  {
    name: 'Bhopal & Sanchi',
    state_name: 'Madhya Pradesh',
    state_code: 'MP',
    tagline: 'City of Lakes, Begum Palaces & UNESCO Great Stupa',
    description: '3rd-century BCE Great Buddhist Stupa of Sanchi, Bhimbetka prehistoric rock shelters, Taj-ul-Masajid, and Bharat Bhavan arts centre.',
    latitude: 23.2599,
    longitude: 77.4126,
    image_url: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Prehistoric tribal heritage, Buddhist monastic history, and Begum architectural legacies.',
    best_time_to_visit: 'October to March',
    aliases: ['Sanchi', 'Bhimbetka'],
    categories: ['Heritage', 'Art & Culture', 'Spiritual'],
    heritage_count: 24,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= BIHAR =================
  {
    name: 'Bodh Gaya & Nalanda',
    state_name: 'Bihar',
    state_code: 'BR',
    tagline: 'Place of Buddha\'s Enlightenment & Ancient University',
    description: 'UNESCO Mahabodhi Temple under the sacred Bodhi Tree, ruins of ancient Nalanda Monastic University, and international Buddhist monasteries.',
    latitude: 24.6961,
    longitude: 84.9869,
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Global Buddhist pilgrimage epicenter, ancient Magadha empire history, and sacred tranquility.',
    best_time_to_visit: 'October to March',
    aliases: ['Bodhgaya', 'Nalanda', 'Rajgir'],
    categories: ['Spiritual', 'Heritage', 'Art & Culture'],
    heritage_count: 25,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= ASSAM =================
  {
    name: 'Guwahati & Majuli',
    state_name: 'Assam',
    state_code: 'AS',
    tagline: 'Kamakhya Tantric Shrine & World\'s Largest River Island',
    description: 'Sacred hilltop Kamakhya Shaktipeeth, Majuli river island sattras preserving traditional mask-making, and Brahmaputra sunset cruises.',
    latitude: 26.1445,
    longitude: 91.7362,
    image_url: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Neo-Vaishnavite monastic dance (Sattriya), Muga golden silk weaving, and vibrant Bihu harvest folklore.',
    best_time_to_visit: 'October to April',
    aliases: ['Majuli', 'Pragjyotishpura'],
    categories: ['Art & Culture', 'Spiritual', 'Workshops', 'Nature'],
    heritage_count: 20,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= MEGHALAYA =================
  {
    name: 'Shillong & Cherrapunji',
    state_name: 'Meghalaya',
    state_code: 'ML',
    tagline: 'Scotland of the East & Living Root Bridges',
    description: 'Double Decker Living Root Bridges grown from Ficus elastica roots, Nohkalikai Falls, Dawki crystalline river, and rock music cafe culture in Shillong.',
    latitude: 25.5788,
    longitude: 91.8933,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Matrilineal Khasi society, indigenous bio-engineering, and vibrant indie music concerts.',
    best_time_to_visit: 'September to May',
    aliases: ['Sohra', 'Cherrapunjee', 'Dawki'],
    categories: ['Nature', 'Adventure', 'Music', 'Hidden Gems'],
    heritage_count: 17,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= SIKKIM =================
  {
    name: 'Gangtok & Pelling',
    state_name: 'Sikkim',
    state_code: 'SK',
    tagline: 'Himalayan Ridge Citadel & Ancient Gompas',
    description: 'Rumtek Monastery golden stupa, panoramic views of Mt. Kanchenjunga from Pelling, Namgyal Institute of Tibetology, and organic MG Marg promenade.',
    latitude: 27.3389,
    longitude: 88.6065,
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Tibetan-Lepcha-Bhutia synthesis, organic culinary culture, and vibrant Losar Buddhist festivals.',
    best_time_to_visit: 'March to June, October to December',
    aliases: ['Pelling', 'Gangtok'],
    categories: ['Spiritual', 'Nature', 'Local Food', 'Adventure'],
    heritage_count: 16,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= DELHI (UT) =================
  {
    name: 'Delhi',
    state_name: 'Delhi',
    state_code: 'DL',
    tagline: 'The Seven Historic Capitals of India',
    description: 'Red Fort, Qutub Minar, Humayun\'s Tomb, Chandni Chowk Mughal food labyrinths, Nizamuddin Dargah Sufi Qawwalis, and modern art galleries.',
    latitude: 28.6139,
    longitude: 77.2090,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Sultanate, Mughal, and British colonial layered history harmonized with street food culture and artisan bazaars.',
    best_time_to_visit: 'October to March',
    aliases: ['New Delhi', 'Old Delhi', 'Dilli', 'Shahjahanabad'],
    categories: ['Heritage', 'Local Food', 'Art & Culture', 'Shopping', 'Music'],
    heritage_count: 50,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 1'
  },

  // ================= GOA =================
  {
    name: 'Goa',
    state_name: 'Goa',
    state_code: 'GA',
    tagline: 'Latin Quarters, Baroque Cathedrals & Konkan Coast',
    description: 'Fontainhas colorful heritage quarter, Basilica of Bom Jesus, spice plantation tours in Ponda, Palolem quiet beaches, and Goan fish thalis.',
    latitude: 15.2993,
    longitude: 74.1240,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Indo-Portuguese architecture, traditional fado music, artisanal feni distillations, and susegad coastal lifestyle.',
    best_time_to_visit: 'October to April',
    aliases: ['Panaji', 'Old Goa', 'Fontainhas', 'Margao'],
    categories: ['Heritage', 'Local Food', 'Nightlife', 'Nature', 'Art & Culture'],
    heritage_count: 22,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= JAMMU & KASHMIR (UT) =================
  {
    name: 'Srinagar',
    state_name: 'Jammu and Kashmir',
    state_code: 'JK',
    tagline: 'Paradise Valley, Dal Lake Shikaras & Pashmina Craft',
    description: 'Historic wooden houseboats on Dal Lake, Nishat and Shalimar Mughal Gardens, Jama Masjid wooden architecture, and Sozni needlework studios.',
    latitude: 34.0837,
    longitude: 74.7973,
    image_url: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Kashmiri Wazwan 36-course royal feasts, Kahwa saffron tea, walnut wood carving, and Sufi saint shrines.',
    best_time_to_visit: 'April to October, December to February for snow',
    aliases: ['Kashmir', 'Dal Lake'],
    categories: ['Heritage', 'Art & Culture', 'Nature', 'Local Food', 'Workshops'],
    heritage_count: 26,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= LADAKH (UT) =================
  {
    name: 'Leh & Ladakh',
    state_name: 'Ladakh',
    state_code: 'LA',
    tagline: 'High-Altitude Citadel of Gompas & Azure Alpine Lakes',
    description: '9-storey Leh Palace, Thiksey & Hemis cliffside monasteries, Nubra Valley sand dunes with double-humped camels, and turquoise Pangong Lake.',
    latitude: 34.1526,
    longitude: 77.5771,
    image_url: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Tibetan Buddhist monastic masked cham dances, eco-conscious Ladakhi solar architecture, and butter tea hospitality.',
    best_time_to_visit: 'May to September',
    aliases: ['Ladakh', 'Nubra', 'Pangong'],
    categories: ['Spiritual', 'Adventure', 'Nature', 'Photography'],
    heritage_count: 24,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= PUDUCHERRY (UT) =================
  {
    name: 'Puducherry',
    state_name: 'Puducherry',
    state_code: 'PY',
    tagline: 'French Colonial Promenade & Spiritual Auroville',
    description: 'Yellow-mustard colonial villas of White Town, Sri Aurobindo Ashram, Matrimandir golden sphere in Auroville, and seaside croissants.',
    latitude: 11.9416,
    longitude: 79.8083,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Franco-Tamil architectural blend, organic farming and experimental crafts in Auroville, and quiet bicycle trails.',
    best_time_to_visit: 'October to March',
    aliases: ['Pondicherry', 'Auroville', 'Pondy'],
    categories: ['Heritage', 'Spiritual', 'Local Food', 'Art & Culture'],
    heritage_count: 18,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= ANDAMAN & NICOBAR (UT) =================
  {
    name: 'Port Blair & Havelock',
    state_name: 'Andaman and Nicobar Islands',
    state_code: 'AN',
    tagline: 'Historic Cellular Jail & Tropical Coral Reefs',
    description: 'National Memorial Cellular Jail sound & light show, Radhanagar Beach sunsets, scuba diving at Elephant Beach, and limestone caves.',
    latitude: 11.6234,
    longitude: 92.7265,
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Freedom struggle memorial history intertwined with pristine marine coral ecosystems.',
    best_time_to_visit: 'October to May',
    aliases: ['Havelock', 'Swaraj Dweep', 'Neil Island'],
    categories: ['Heritage', 'Nature', 'Adventure', 'Couple'],
    heritage_count: 12,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },

  // ================= CHANDIGARH (UT) =================
  {
    name: 'Chandigarh',
    state_name: 'Chandigarh',
    state_code: 'CH',
    tagline: 'Modernist City Beautiful & Le Corbusier Heritage',
    description: 'UNESCO World Heritage Capitol Complex designed by Le Corbusier, Nek Chand\'s iconic Rock Garden made of recycled ceramics, and Rose Garden.',
    latitude: 30.7333,
    longitude: 76.7794,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    culture_summary: '20th-century modernist urban architecture harmonized with Punjabi and Haryanvi culinary warmth.',
    best_time_to_visit: 'October to March',
    aliases: ['The City Beautiful'],
    categories: ['Heritage', 'Art & Culture', 'Nature', 'Family'],
    heritage_count: 10,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= DADRA & NAGAR HAVELI AND DAMAN & DIU (UT) =================
  {
    name: 'Diu & Daman',
    state_name: 'Dadra and Nagar Haveli and Daman and Diu',
    state_code: 'DNHDD',
    tagline: 'Portuguese Sea Fortresses & Coastal Serenity',
    description: '16th-century Diu Sea Fort with ocean-facing cannons, St. Paul\'s Church, Nagoa beach seashell crafts, and Warli tribal arts in Silvassa.',
    latitude: 20.7144,
    longitude: 70.9874,
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Portuguese maritime trade heritage alongside indigenous Warli tribal painting workshops.',
    best_time_to_visit: 'October to May',
    aliases: ['Diu', 'Daman', 'Silvassa'],
    categories: ['Heritage', 'Nature', 'Art & Culture'],
    heritage_count: 11,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= LAKSHADWEEP (UT) =================
  {
    name: 'Kavaratti & Bangaram',
    state_name: 'Lakshadweep',
    state_code: 'LD',
    tagline: 'Pristine Coral Atolls & Coconut Coir Crafts',
    description: 'Untouched azure lagoons, marine aquarium, traditional wood-carved Ujra Mosque, and water sports at Bangaram Atoll.',
    latitude: 10.5669,
    longitude: 72.6420,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Eco-conscious island traditions, coconut coir handicrafts, and vibrant coral reef life.',
    best_time_to_visit: 'October to May',
    aliases: ['Bangaram', 'Agatti', 'Kavaratti'],
    categories: ['Nature', 'Adventure', 'Couple', 'Hidden Gems'],
    heritage_count: 8,
    is_popular: 0,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },

  // ================= ARUNACHAL PRADESH =================
  {
    name: 'Tawang & Ziro',
    state_name: 'Arunachal Pradesh',
    state_code: 'AR',
    tagline: 'Monastic Citadels & Sacred Apatani Pine Valleys',
    description: '400-year-old Tawang Buddhist Monastery, Sela Pass glacial heights, Ziro Valley UNESCO cultural landscape, and Apatani bamboo architecture.',
    latitude: 27.5861,
    longitude: 91.8594,
    image_url: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Monpa and Apatani tribal traditions, handmade paper from tree bark, and outdoor music festivals.',
    best_time_to_visit: 'March to October',
    aliases: ['Tawang', 'Ziro Valley', 'Bomdila'],
    categories: ['Spiritual', 'Nature', 'Art & Culture', 'Hidden Gems'],
    heritage_count: 14,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= CHHATTISGARH =================
  {
    name: 'Bastar & Jagdalpur',
    state_name: 'Chhattisgarh',
    state_code: 'CG',
    tagline: 'Tribal Craft Capital & Chitrakote Horseshoe Falls',
    description: 'Chitrakote and Tirathgarh waterfalls, Dhokra bell-metal lost wax casting masters, and Bastar Dussehra 75-day festival traditions.',
    latitude: 19.0734,
    longitude: 82.0287,
    image_url: 'https://images.unsplash.com/photo-1626014303757-64663673fdf8?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Ancient tribal craft guilds, terracotta and wrought-iron smiths, and sacred forest deities.',
    best_time_to_visit: 'October to March',
    aliases: ['Jagdalpur', 'Bastar'],
    categories: ['Art & Culture', 'Nature', 'Workshops', 'Hidden Gems'],
    heritage_count: 15,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= ANDHRA PRADESH =================
  {
    name: 'Visakhapatnam & Araku',
    state_name: 'Andhra Pradesh',
    state_code: 'AP',
    tagline: 'Coastal Port & Organic Coffee Valley',
    description: 'Submarine museum on beachfront, Kailasagiri hill, Borra Caves million-year stalactites, and organic tribal Araku coffee plantations.',
    latitude: 17.6868,
    longitude: 83.2185,
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Coastal Andhra culture, Dhimsa tribal dance, and spicy Andhra thalis with gongura pachadi.',
    best_time_to_visit: 'October to March',
    aliases: ['Vizag', 'Araku Valley'],
    categories: ['Nature', 'Local Food', 'Adventure', 'Heritage'],
    heritage_count: 16,
    is_popular: 1,
    is_heritage_hub: 0,
    tier: 'Tier 2'
  },
  {
    name: 'Tirupati & Lepakshi',
    state_name: 'Andhra Pradesh',
    state_code: 'AP',
    tagline: 'Sacred Hill Shrines & Vijayanagara Hanging Pillar',
    description: 'Sri Venkateswara Swamy Temple at Tirumala, Veerabhadra temple with hanging pillar at Lepakshi, and Kalamkari fabric painting.',
    latitude: 13.6288,
    longitude: 79.4192,
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Centuries-old pilgrimage rituals, woodcarving masters, and GI-certified Tirupati Laddu.',
    best_time_to_visit: 'September to March',
    aliases: ['Tirupati', 'Tirumala', 'Lepakshi'],
    categories: ['Spiritual', 'Heritage', 'Workshops'],
    heritage_count: 18,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= NAGALAND =================
  {
    name: 'Kohima & Khonoma',
    state_name: 'Nagaland',
    state_code: 'NL',
    tagline: 'Hornbill Festival & India\'s First Green Eco-Village',
    description: 'Kisama Heritage Village home to the Hornbill Festival, Kohima WWII War Cemetery, and Khonoma Angami tribal terraced farming.',
    latitude: 25.6751,
    longitude: 94.1086,
    image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Rich Naga warrior clan traditions, bamboo and cane craft, and communal eco-conservation.',
    best_time_to_visit: 'October to May (December for Hornbill)',
    aliases: ['Khonoma', 'Kisama'],
    categories: ['Art & Culture', 'Festivals', 'Nature', 'Hidden Gems'],
    heritage_count: 14,
    is_popular: 1,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= MANIPUR =================
  {
    name: 'Imphal & Loktak Lake',
    state_name: 'Manipur',
    state_code: 'MN',
    tagline: 'Floating Phumdis & Mother\'s Market of Artisans',
    description: 'Keibul Lamjao National Park on floating Loktak lake, Ima Keithel (Asia\'s largest all-women market), and Kangla Fort historical site.',
    latitude: 24.8170,
    longitude: 93.9368,
    image_url: 'https://images.unsplash.com/photo-1596405835955-463df1c3df5e?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Women-led commerce, classic Manipuri Raas dance, and Longpi black earthenware cooking pottery.',
    best_time_to_visit: 'October to April',
    aliases: ['Loktak', 'Moirang'],
    categories: ['Nature', 'Shopping', 'Art & Culture', 'Hidden Gems'],
    heritage_count: 13,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= TRIPURA =================
  {
    name: 'Agartala & Unakoti',
    state_name: 'Tripura',
    state_code: 'TR',
    tagline: 'Water Palaces & Rock-Carved Shiva Reliefs',
    description: 'Neermahal water palace on Rudrasagar lake, Ujjayanta Palace, and massive 8th-century rock-carved Shaivite faces at Unakoti.',
    latitude: 23.8315,
    longitude: 91.2868,
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Royal Manikya dynasty palaces, bamboo root sculpture masters, and lush tea gardens.',
    best_time_to_visit: 'October to March',
    aliases: ['Unakoti', 'Neermahal'],
    categories: ['Heritage', 'Spiritual', 'Nature', 'Hidden Gems'],
    heritage_count: 12,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  },

  // ================= MIZORAM =================
  {
    name: 'Aizawl & Reiek',
    state_name: 'Mizoram',
    state_code: 'MZ',
    tagline: 'Misty Hilltops, Cheraw Dance & Bamboo Architecture',
    description: 'Dramatic ridgeline vistas in Aizawl, Solomon\'s Temple, Reiek peak heritage village with typical Mizo huts, and handwoven Puan fabrics.',
    latitude: 23.7271,
    longitude: 92.7176,
    image_url: 'https://images.unsplash.com/photo-1616885375498-500b58e77a11?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Warm Mizo Christian choral traditions, peaceful community life, and vibrant bamboo handicrafts.',
    best_time_to_visit: 'October to April',
    aliases: ['Reiek', 'Champhai'],
    categories: ['Nature', 'Art & Culture', 'Music', 'Hidden Gems'],
    heritage_count: 11,
    is_popular: 0,
    is_heritage_hub: 0,
    tier: 'Tier 3'
  },

  // ================= JHARKHAND =================
  {
    name: 'Ranchi & Deoghar',
    state_name: 'Jharkhand',
    state_code: 'JH',
    tagline: 'Waterfalls & Sacred Baidyanath Jyotirlinga',
    description: 'Sacred Baba Baidyanath temple in Deoghar, Hundru and Jonha waterfalls, and indigenous Sohrai wall mural artist villages.',
    latitude: 23.3441,
    longitude: 85.3096,
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Tribal arts of the Santhal and Munda communities, brass craft of Khunti, and sacred pilgrim trails.',
    best_time_to_visit: 'October to March',
    aliases: ['Deoghar', 'Baidyanath Dham'],
    categories: ['Spiritual', 'Nature', 'Art & Culture', 'Hidden Gems'],
    heritage_count: 14,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 2'
  },

  // ================= HARYANA =================
  {
    name: 'Kurukshetra & Pinjore',
    state_name: 'Haryana',
    state_code: 'HR',
    tagline: 'Epic Mahabharata Heritage & Mughal Terraced Gardens',
    description: 'Brahma Sarovar sacred water reservoir, Jyotisar where the Bhagavad Gita was delivered, and 17th-century Pinjore Gardens.',
    latitude: 29.9695,
    longitude: 76.8783,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    culture_summary: 'Ancient Vedic and epic literature roots, Surajkund crafts mela, and traditional dairy food.',
    best_time_to_visit: 'October to March',
    aliases: ['Pinjore', 'Thanesar'],
    categories: ['Heritage', 'Spiritual', 'Nature'],
    heritage_count: 14,
    is_popular: 0,
    is_heritage_hub: 1,
    tier: 'Tier 3'
  }
];

export async function seedPanIndiaCompleteNetwork() {
  console.log('[Pan-India Complete Network] Synchronizing all 28 States & 8 Union Territories...');

  // 1. Seed States
  const stateMap = {};
  for (const s of PAN_INDIA_STATES_DATASET) {
    const existing = await dbGet('SELECT * FROM states WHERE name = ? OR code = ?', [s.name, s.code]);
    if (existing) {
      await dbRun(
        `UPDATE states SET 
          region = ?, is_union_territory = ?, image_url = ?, description = ?, heritage_count = ?
         WHERE id = ?`,
        [s.region, s.is_union_territory, s.image_url, s.description, s.heritage_count, existing.id]
      );
      stateMap[s.name] = existing.id;
    } else {
      const res = await dbRun(
        `INSERT INTO states (name, code, region, is_union_territory, image_url, description, heritage_count)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [s.name, s.code, s.region, s.is_union_territory, s.image_url, s.description, s.heritage_count]
      );
      stateMap[s.name] = res.lastID;
    }
  }

  // 2. Seed Cities & Destinations
  let seededCities = 0;
  for (const c of PAN_INDIA_CITIES_DATASET) {
    const stateId = stateMap[c.state_name];
    const existingCity = await dbGet(
      'SELECT * FROM cities WHERE LOWER(name) = LOWER(?)',
      [c.name]
    );

    const aliasesJson = JSON.stringify(c.aliases || []);
    const categoriesJson = JSON.stringify(c.categories || []);

    if (existingCity) {
      await dbRun(
        `UPDATE cities SET
          state_id = ?, state_name = ?, state_code = ?, tagline = ?, description = ?,
          latitude = ?, longitude = ?, image_url = ?, culture_summary = ?, best_time_to_visit = ?,
          aliases = ?, categories = ?, heritage_count = ?, is_popular = ?, is_heritage_hub = ?, tier = ?
         WHERE id = ?`,
        [
          stateId || existingCity.state_id,
          c.state_name,
          c.state_code,
          c.tagline,
          c.description,
          c.latitude,
          c.longitude,
          c.image_url,
          c.culture_summary,
          c.best_time_to_visit,
          aliasesJson,
          categoriesJson,
          c.heritage_count || 10,
          c.is_popular ? 1 : 0,
          c.is_heritage_hub ? 1 : 0,
          c.tier || 'Tier 2',
          existingCity.id
        ]
      );
    } else {
      await dbRun(
        `INSERT INTO cities (
          name, state_id, state_name, state_code, tagline, description,
          latitude, longitude, image_url, culture_summary, best_time_to_visit,
          aliases, categories, heritage_count, is_popular, is_heritage_hub, tier
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          c.name,
          stateId,
          c.state_name,
          c.state_code,
          c.tagline,
          c.description,
          c.latitude,
          c.longitude,
          c.image_url,
          c.culture_summary,
          c.best_time_to_visit,
          aliasesJson,
          categoriesJson,
          c.heritage_count || 10,
          c.is_popular ? 1 : 0,
          c.is_heritage_hub ? 1 : 0,
          c.tier || 'Tier 2'
        ]
      );
      seededCities++;
    }
  }

  // Update experience counts on all states
  const allStates = await dbAll('SELECT * FROM states');
  for (const st of allStates) {
    const expCount = await dbGet('SELECT COUNT(*) as c FROM experiences WHERE state = ?', [st.name]);
    const citiesCount = await dbGet('SELECT COUNT(*) as c FROM cities WHERE state_id = ? OR state_name = ?', [st.id, st.name]);
    const totalExp = (expCount?.c || 0) + (citiesCount?.c || 1) * 3;
    await dbRun('UPDATE states SET heritage_count = ? WHERE id = ?', [Math.max(st.heritage_count || 0, citiesCount?.c || 2), st.id]);
  }

  console.log(`[Pan-India Complete Network] Seeded/updated 36 States/UTs and ${PAN_INDIA_CITIES_DATASET.length} Cities successfully.`);
}
