import { dbRun, dbAll } from '../db/db.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MAHARASHTRA_EXPERIENCES = [
  // 1. Alibag
  {
    id: 7001,
    title: 'Alibag Beach',
    tagline: 'Iconic black-sand shoreline with horse buggy rides & views of Kolaba Fort',
    description: 'Famous for its hard, flat black sand shoreline, scenic horse buggy rides, water scooter trails, and sweeping sunset panoramas of the Arabian Sea and historic Kolaba Fort.',
    category: 'Nature & Wildlife',
    city: 'Alibag',
    state: 'Maharashtra',
    area_name: 'Alibag Coastline, Raigad District',
    price: 0,
    rating: 4.82,
    review_count: 1420,
    approx_duration_mins: 90,
    image_url: 'https://res.cloudinary.com/dyiffrkzh/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_center,h_400,q_auto,w_700/v1681315583/bbj/c9qg14p8jgtovznvolmu.jpg',
    image_urls: JSON.stringify([
      'https://res.cloudinary.com/dyiffrkzh/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_center,h_400,q_auto,w_700/v1681315583/bbj/c9qg14p8jgtovznvolmu.jpg',
    ]),
    tags: JSON.stringify(['beach', 'alibag', 'water-sports', 'sunset', 'maharashtra', 'verified']),
    latitude: 18.6414,
    longitude: 72.8722,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7002,
    title: 'Kolaba Fort',
    tagline: '300-year-old Maratha sea fortress accessible by foot or horse cart during low tide',
    description: 'Fortified naval stronghold built by Chhatrapati Shivaji Maharaj in 1680. Features colossal sea-facing stone bastions, freshwater temple wells amidst the sea, and historic brass cannons.',
    category: 'Heritage & History',
    city: 'Alibag',
    state: 'Maharashtra',
    area_name: 'Alibag Sea Shoal, Raigad',
    price: 25,
    rating: 4.88,
    review_count: 1890,
    approx_duration_mins: 120,
    image_url: 'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1709191462_kulaba_fort.jpg.webp',
    image_urls: JSON.stringify([
      'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1709191462_kulaba_fort.jpg.webp',
    ]),
    tags: JSON.stringify(['fort', 'maratha', 'kolaba', 'sea-fort', 'alibag', 'verified']),
    latitude: 18.6403,
    longitude: 72.8611,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7003,
    title: 'Kashid Beach',
    tagline: 'Pristine white-sand shoreline framed by casuarina groves and roaring Arabian Sea waves',
    description: 'Renowned as one of the cleanest and most scenic white-sand beaches on the Konkan coast. Famous for parasailing, banana boat rides, and tranquil casuarina tree canopies.',
    category: 'Nature & Wildlife',
    city: 'Alibag',
    state: 'Maharashtra',
    area_name: 'Kashid Coastal Highway, Murud-Alibag',
    price: 0,
    rating: 4.85,
    review_count: 2130,
    approx_duration_mins: 120,
    image_url: 'https://hotelsinalibaug.in/assets/images/alibaug-sea-view.webp',
    image_urls: JSON.stringify([
      'https://hotelsinalibaug.in/assets/images/alibaug-sea-view.webp',
    ]),
    tags: JSON.stringify(['kashid', 'white-sand', 'beach', 'alibag', 'konkan', 'verified']),
    latitude: 18.4414,
    longitude: 72.9097,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 2. Chhatrapati Sambhajinagar
  {
    id: 7004,
    title: 'Ajanta Caves',
    tagline: 'UNESCO World Heritage 2nd-century BCE rock-cut Buddhist cave temples and master frescoes',
    description: 'A horse-shoe shaped gorge preserving 30 rock-cut monumental caves. Celebrated globally for exquisite tempera murals, bodhisattva sculptures, and monolithic viharas.',
    category: 'Art & Culture',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    area_name: 'Waghur River Gorge, Ajanta',
    price: 40,
    rating: 4.96,
    review_count: 5210,
    approx_duration_mins: 240,
    image_url: 'https://s7ap1.scene7.com/is/image/incredibleindia/ajanta-caves-chhatrapati-sambhaji-nagar-maharashtra-attr-hero-2?qlt=82&ts=1727010576169',
    image_urls: JSON.stringify([
      'https://s7ap1.scene7.com/is/image/incredibleindia/ajanta-caves-chhatrapati-sambhaji-nagar-maharashtra-attr-hero-2?qlt=82&ts=1727010576169',
    ]),
    tags: JSON.stringify(['ajanta', 'unesco', 'caves', 'buddhist', 'art', 'murals', 'verified']),
    latitude: 20.5519,
    longitude: 75.7033,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7005,
    title: 'Ellora Caves',
    tagline: 'UNESCO monolithic Kailash temple carved top-down from a single basalt cliff',
    description: 'A monumental rock-cut cave complex spanning Buddhist, Hindu, and Jain sanctuaries. Features the astonishing Cave 16 Kailasa temple, the world’s largest top-to-bottom monolithic stone excavation.',
    category: 'Heritage & History',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    area_name: 'Charanandri Hills, Ellora',
    price: 40,
    rating: 4.97,
    review_count: 5890,
    approx_duration_mins: 240,
    image_url: 'https://res.klook.com/images/w_1200,h_630,c_fill,q_65/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/kdhxyfyruusxsrqqwyvd/ElloraCavesEntryTicketwithOptionalGuide-Klook.jpg',
    image_urls: JSON.stringify([
      'https://res.klook.com/images/w_1200,h_630,c_fill,q_65/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/kdhxyfyruusxsrqqwyvd/ElloraCavesEntryTicketwithOptionalGuide-Klook.jpg',
    ]),
    tags: JSON.stringify(['ellora', 'kailash-temple', 'unesco', 'monolithic', 'caves', 'verified']),
    latitude: 20.0268,
    longitude: 75.1793,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7006,
    title: 'Bibi Ka Maqbara',
    tagline: 'Tomb of Dilras Banu Begum, the architectural Mughal masterpiece known as the Taj of the Deccan',
    description: 'Commissioned in 1660 by Mughal Emperor Aurangzeb in memory of his chief consort. Features octagonal marble screens, minarets, Charbagh water gardens, and intricate stucco plaster motifs.',
    category: 'Heritage & History',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    area_name: 'Begumpura, Chhatrapati Sambhajinagar',
    price: 25,
    rating: 4.86,
    review_count: 3120,
    approx_duration_mins: 90,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/BB_ka_Maqbara_%E0%A4%AC%E0%A5%80%E0%A4%AC%E0%A5%80_%E0%A4%95%E0%A4%BE_%E0%A4%AE%E0%A4%95%E0%A4%AC%E0%A4%B0%E0%A4%BE.jpg',
    image_urls: JSON.stringify([
      'https://upload.wikimedia.org/wikipedia/commons/b/b2/BB_ka_Maqbara_%E0%A4%AC%E0%A5%80%E0%A4%AC%E0%A5%80_%E0%A4%95%E0%A4%BE_%E0%A4%AE%E0%A4%95%E0%A4%AC%E0%A4%B0%E0%A4%BE.jpg',
    ]),
    tags: JSON.stringify(['bibi-ka-maqbara', 'mughal', 'taj-of-deccan', 'architecture', 'verified']),
    latitude: 19.9014,
    longitude: 75.3203,
    is_indoor: 0,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 3. Lonavala
  {
    id: 7007,
    title: 'Lonavala (Tiger’s Leap & Bhushi Dam)',
    tagline: 'Sahyadri hill resort celebrated for dramatic misty cliff edges, cascades, and chikki bazaars',
    description: 'Scenic hill getaway 2,000 feet above sea level. Experience panoramic valley sweeps at Tiger’s Leap, the foaming overflow of Bhushi Dam, and traditional artisanal chikki workshops.',
    category: 'Nature & Wildlife',
    city: 'Lonavala',
    state: 'Maharashtra',
    area_name: 'Tiger’s Leap & Bhushi Dam Ridge, Lonavala',
    price: 0,
    rating: 4.84,
    review_count: 3670,
    approx_duration_mins: 180,
    image_url: 'https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_lonavala_tv_destination_img_2_l_664_1000.jpg',
    image_urls: JSON.stringify([
      'https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_lonavala_tv_destination_img_2_l_664_1000.jpg',
    ]),
    tags: JSON.stringify(['lonavala', 'tigers-leap', 'bhushi-dam', 'waterfall', 'hills', 'verified']),
    latitude: 18.7557,
    longitude: 73.4091,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7008,
    title: 'Khandala (Duke’s Nose & Valley Overlooks)',
    tagline: 'Iconic Western Ghats ravine sanctuary famed for Duke’s Nose peak and monsoon mist',
    description: 'Adjoining Lonavala, Khandala is known for the dramatic cliff face of Duke’s Nose (Nagphani), lush Bhor Ghat canyons, cascading monsoon streams, and panoramic highway overlooks.',
    category: 'Nature & Wildlife',
    city: 'Lonavala',
    state: 'Maharashtra',
    area_name: 'Duke’s Nose & Amrutanjan Point, Khandala',
    price: 0,
    rating: 4.81,
    review_count: 2450,
    approx_duration_mins: 120,
    image_url: 'https://www.hlimg.com/images/things2do/738X538/places-to-visit-close_1507816802t.jpg',
    image_urls: JSON.stringify([
      'https://www.hlimg.com/images/things2do/738X538/places-to-visit-close_1507816802t.jpg',
    ]),
    tags: JSON.stringify(['khandala', 'dukes-nose', 'bhor-ghat', 'canyon', 'viewpoint', 'verified']),
    latitude: 18.7497,
    longitude: 73.3768,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7009,
    title: 'Rajmachi Fort',
    tagline: 'Twin hilltop fortresses Shrivardhan and Manaranjan guarding historic Borghat trade route',
    description: 'A legendary Maratha trekking destination perched high in the Sahyadris. Offers rugged stone ramparts, ancient rock caves, Machi village hospitality, and sweeping canyon views.',
    category: 'Heritage & History',
    city: 'Lonavala',
    state: 'Maharashtra',
    area_name: 'Rajmachi Plateau, Sahyadri Range',
    price: 0,
    rating: 4.89,
    review_count: 1880,
    approx_duration_mins: 240,
    image_url: 'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1709015548_59722d0804ae8d4c05d6df2a_5940c7a8cfa0955807271807_1500654856394.jpg.webp',
    image_urls: JSON.stringify([
      'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1709015548_59722d0804ae8d4c05d6df2a_5940c7a8cfa0955807271807_1500654856394.jpg.webp',
    ]),
    tags: JSON.stringify(['rajmachi', 'fort', 'trekking', 'sahyadri', 'borghat', 'verified']),
    latitude: 18.8272,
    longitude: 73.3986,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 4. Nagpur
  {
    id: 7010,
    title: 'Deekshabhoomi',
    tagline: 'Largest hollow Buddhist stupa in Asia where Dr. B.R. Ambedkar embraced Buddhism in 1956',
    description: 'A monumental sacred pilgrimage site designed with Dhauli-style architecture. Paved with Dholpur sandstone and granite, featuring a soaring 120-foot dome, marble Buddha shrines, and peaceful lawns.',
    category: 'Spiritual & Wellness',
    city: 'Nagpur',
    state: 'Maharashtra',
    area_name: 'Ramdaspeth, South Nagpur',
    price: 0,
    rating: 4.94,
    review_count: 4890,
    approx_duration_mins: 90,
    image_url: 'https://nagpurtourism.co.in/images/v2/places-to-visit/deeksha-bhoomi-nagpur-tourism-header.jpg',
    image_urls: JSON.stringify([
      'https://nagpurtourism.co.in/images/v2/places-to-visit/deeksha-bhoomi-nagpur-tourism-header.jpg',
    ]),
    tags: JSON.stringify(['deekshabhoomi', 'stupa', 'ambedkar', 'buddhism', 'nagpur', 'verified']),
    latitude: 21.1276,
    longitude: 79.0664,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7011,
    title: 'Futala Lake',
    tagline: 'Historic 200-year-old lake built by the Bhonsle kings, famous for vibrant sunset promenades',
    description: 'Spanning 60 acres, Futala Lake is flanked by colorful evening chowpatty food stalls, a modern illuminated dancing fountain show, and tranquil paved waterfront walking trails.',
    category: 'Nature & Wildlife',
    city: 'Nagpur',
    state: 'Maharashtra',
    area_name: 'West Nagpur Promenade, Telangkhedi',
    price: 0,
    rating: 4.83,
    review_count: 2780,
    approx_duration_mins: 60,
    image_url: 'https://spmiasacademy.com/currentaffairs/wp-content/uploads/2026/09/image-10-1024x576.jpeg',
    image_urls: JSON.stringify([
      'https://spmiasacademy.com/currentaffairs/wp-content/uploads/2026/09/image-10-1024x576.jpeg',
    ]),
    tags: JSON.stringify(['lake', 'futala', 'promenade', 'nagpur', 'sunset', 'verified']),
    latitude: 21.1539,
    longitude: 79.0433,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7012,
    title: 'Pench Tiger Reserve',
    tagline: 'Rudyard Kipling’s The Jungle Book tiger wilderness along the serene Pench River',
    description: 'Rich teak and mixed forest sanctuary harboring royal Bengal tigers, Indian leopards, wild dogs, and over 285 species of resident and migratory birds across scenic riverine tracks.',
    category: 'Nature & Wildlife',
    city: 'Nagpur',
    state: 'Maharashtra',
    area_name: 'Ramtek & Mansar Range, Nagpur District',
    price: 500,
    rating: 4.91,
    review_count: 3410,
    approx_duration_mins: 240,
    image_url: 'https://www.culturalsafaritours.com/wp-content/uploads/2020/08/penchsafari.jpg',
    image_urls: JSON.stringify([
      'https://www.culturalsafaritours.com/wp-content/uploads/2020/08/penchsafari.jpg',
    ]),
    tags: JSON.stringify(['tiger-reserve', 'pench', 'safari', 'wildlife', 'jungle-book', 'verified']),
    latitude: 21.6542,
    longitude: 79.2975,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 5. Nashik
  {
    id: 7013,
    title: 'Trimbakeshwar Shiva Temple',
    tagline: 'Ancient Jyotirlinga temple at the source of sacred River Godavari built of black basalt',
    description: 'One of the twelve sacred Jyotirlingas, extraordinary for its three-faced linga embodying Brahma, Vishnu, and Shiva. Surrounded by towering Brahmagiri hills and Kushavarta holy kunda.',
    category: 'Spiritual & Wellness',
    city: 'Nashik',
    state: 'Maharashtra',
    area_name: 'Trimbak, Brahmagiri Foothills, Nashik',
    price: 0,
    rating: 4.95,
    review_count: 6120,
    approx_duration_mins: 120,
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Trimbakeshwar_Temple-Nashik-Maharashtra-1.jpg/1280px-Trimbakeshwar_Temple-Nashik-Maharashtra-1.jpg',
    image_urls: JSON.stringify([
      'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Trimbakeshwar_Temple-Nashik-Maharashtra-1.jpg/1280px-Trimbakeshwar_Temple-Nashik-Maharashtra-1.jpg',
    ]),
    tags: JSON.stringify(['trimbakeshwar', 'jyotirlinga', 'shiva', 'godavari', 'nashik', 'verified']),
    latitude: 19.9325,
    longitude: 73.5306,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7014,
    title: 'Sula Vineyards',
    tagline: 'Pioneering Indian winery offering guided cellar barrel tastings and Gangapur lake panoramas',
    description: 'Set amidst rolling grape vines, Sula is the epicenter of Nashik’s wine country. Enjoy guided winery fermentation tours, oak barrel room tastings, and sunset amphitheater dining.',
    category: 'Food & Culinary',
    city: 'Nashik',
    state: 'Maharashtra',
    area_name: 'Gangapur-Savargaon Road, Nashik',
    price: 400,
    rating: 4.89,
    review_count: 5320,
    approx_duration_mins: 150,
    image_url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3f/8e/3d/a-view-from-the-vineyards.jpg?w=1200&h=1200&s=1',
    image_urls: JSON.stringify([
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3f/8e/3d/a-view-from-the-vineyards.jpg?w=1200&h=1200&s=1',
    ]),
    tags: JSON.stringify(['wine', 'vineyard', 'sula', 'nashik', 'tasting', 'verified']),
    latitude: 20.0072,
    longitude: 73.6888,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7015,
    title: 'Pandavleni Caves',
    tagline: '24 ancient Hinayana Buddhist rock-cut caves carved between 1st century BCE & 3rd century CE',
    description: 'Perched on Trirashmi hill, these monastic caves feature exquisite water cistern systems, Chaitya prayer halls, ornate pillar sculptures, and historic Brahmi stone inscriptions.',
    category: 'Heritage & History',
    city: 'Nashik',
    state: 'Maharashtra',
    area_name: 'Tirashmi Hill, Mumbai-Agra Highway, Nashik',
    price: 25,
    rating: 4.86,
    review_count: 2210,
    approx_duration_mins: 90,
    image_url: 'https://cdn.s3waas.gov.in/s3b3967a0e938dc2a6340e258630febd5a/uploads/bfi_thumb/2019011832-olwbukos7qk9rsyvub240rbka7wuopmv84w1cqs2oa.png',
    image_urls: JSON.stringify([
      'https://cdn.s3waas.gov.in/s3b3967a0e938dc2a6340e258630febd5a/uploads/bfi_thumb/2019011832-olwbukos7qk9rsyvub240rbka7wuopmv84w1cqs2oa.png',
    ]),
    tags: JSON.stringify(['pandavleni', 'buddhist-caves', 'rock-cut', 'nashik', 'verified']),
    latitude: 19.9619,
    longitude: 73.7486,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 6. Pune
  {
    id: 7016,
    title: 'Shaniwar Wada',
    tagline: '1732 CE fortified Peshwa seat of the Maratha Empire with the towering Dilli Darwaza',
    description: 'Historic seven-story palace fort complex built by Peshwa Bajirao I. Famous for teak-spiked iron gates, fountain courtyards, stone perimeter walls, and dramatic sound & light shows.',
    category: 'Heritage & History',
    city: 'Pune',
    state: 'Maharashtra',
    area_name: 'Shaniwar Peth, Pune Old City',
    price: 25,
    rating: 4.88,
    review_count: 5410,
    approx_duration_mins: 90,
    image_url: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiu9rq-1h6j6dcJeLeZSQy3Agkug8nFpKV08r5YD_nzWhyphenhyphenTnNacY0puajKuKvAdHePu48UHz4WMNF_LslMZVqDrsMuaSWSNTfNqS9ehs6-fGJPWlOeY2KfT_n-jzksTo9u3H6CRmFyNrPU/s1600/Shaniwar+Wada+Gate.jpg',
    image_urls: JSON.stringify([
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiu9rq-1h6j6dcJeLeZSQy3Agkug8nFpKV08r5YD_nzWhyphenhyphenTnNacY0puajKuKvAdHePu48UHz4WMNF_LslMZVqDrsMuaSWSNTfNqS9ehs6-fGJPWlOeY2KfT_n-jzksTo9u3H6CRmFyNrPU/s1600/Shaniwar+Wada+Gate.jpg',
    ]),
    tags: JSON.stringify(['shaniwar-wada', 'peshwa', 'maratha', 'palace-fort', 'pune', 'verified']),
    latitude: 18.5196,
    longitude: 73.8553,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7017,
    title: 'Aga Khan Palace',
    tagline: 'Italian-arched historical palace where Mahatma Gandhi and Kasturba were interned in 1942',
    description: 'Built in 1892 by Sultan Muhammed Shah Aga Khan III. Houses personal artifacts of Mahatma Gandhi, Kasturba Gandhi’s samadhi memorial, spacious manicured lawns, and Italian colonnades.',
    category: 'Heritage & History',
    city: 'Pune',
    state: 'Maharashtra',
    area_name: 'Nagar Road, Kalyani Nagar, Pune',
    price: 25,
    rating: 4.87,
    review_count: 3620,
    approx_duration_mins: 90,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Pune_Palace.jpg',
    image_urls: JSON.stringify([
      'https://upload.wikimedia.org/wikipedia/commons/c/cd/Pune_Palace.jpg',
    ]),
    tags: JSON.stringify(['aga-khan-palace', 'gandhi', 'memorial', 'history', 'pune', 'verified']),
    latitude: 18.5524,
    longitude: 73.9015,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7018,
    title: 'Sinhagad Fort',
    tagline: '1,312m Sahyadri cliff bastion commemorating Tanaji Malusare’s legendary 1670 battle',
    description: 'Perched on an isolated cliff of the Bhuleshwar range. Famous for Kalyan Darwaza, Tanaji Malusare’s memorial, panoramic Khadakwasla dam views, and traditional pithla bhakri food stalls.',
    category: 'Heritage & History',
    city: 'Pune',
    state: 'Maharashtra',
    area_name: 'Thoptewadi, Haveli Taluka, Pune',
    price: 50,
    rating: 4.92,
    review_count: 4790,
    approx_duration_mins: 180,
    image_url: 'https://www.mtdc.co.in/wp-content/uploads/2020/01/19740-640x445.jpg',
    image_urls: JSON.stringify([
      'https://www.mtdc.co.in/wp-content/uploads/2020/01/19740-640x445.jpg',
    ]),
    tags: JSON.stringify(['sinhagad', 'fort', 'maratha', 'tanaji', 'pune', 'trekking', 'verified']),
    latitude: 18.3663,
    longitude: 73.7558,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },

  // 7. Kolhapur
  {
    id: 7019,
    title: 'Mahalakshmi Temple (Ambabai)',
    tagline: '7th-century Chalukyan Shakti Peetha where sunset sun rays illuminate the Goddess',
    description: 'Renowned as Dakshin Kashi, built in Hemadpanthi architectural style. Revered for the monolithic black stone idol of Goddess Mahalakshmi and the annual Kirnotsav solar phenomenon.',
    category: 'Spiritual & Wellness',
    city: 'Kolhapur',
    state: 'Maharashtra',
    area_name: 'Mahadwar Road, B Ward, Kolhapur',
    price: 0,
    rating: 4.96,
    review_count: 5120,
    approx_duration_mins: 90,
    image_url: 'https://www.kolhapurtourism.org/wp-content/uploads/2016/04/n-mahalaxmi-temple-1.jpg',
    image_urls: JSON.stringify([
      'https://www.kolhapurtourism.org/wp-content/uploads/2016/04/n-mahalaxmi-temple-1.jpg',
      'https://www.kolhapurtourism.org/our-destination/mahalaxmi-temple-2/',
    ]),
    tags: JSON.stringify(['mahalakshmi', 'ambabai', 'shakti-peetha', 'temple', 'kolhapur', 'verified']),
    latitude: 16.6944,
    longitude: 74.2238,
    is_indoor: 1,
    is_rain_safe: 1,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 1,
    wheelchair_accessible: 1,
    is_active: 1,
    source: 'user_curated_link',
  },
  {
    id: 7020,
    title: 'Panhala Fort',
    tagline: 'Largest hill fort in the Deccan, celebrated for Sajja Kothi and Teen Darwaza',
    description: 'Built between 1178 and 1209 CE, Panhala played a crucial role in Chhatrapati Shivaji Maharaj’s reign. Features deep moats, massive granaries (Ambar Khana), and sweeping views of the Sahyadris.',
    category: 'Heritage & History',
    city: 'Kolhapur',
    state: 'Maharashtra',
    area_name: 'Panhala Hill, Kolhapur District',
    price: 0,
    rating: 4.88,
    review_count: 2650,
    approx_duration_mins: 120,
    image_url: 'https://www.hindujagruti.org/wp-content/uploads/2015/02/Panhala_640.jpg',
    image_urls: JSON.stringify([
      'https://www.hindujagruti.org/wp-content/uploads/2015/02/Panhala_640.jpg',
    ]),
    tags: JSON.stringify(['panhala', 'fort', 'maratha', 'kolhapur', 'history', 'verified']),
    latitude: 16.8117,
    longitude: 74.1086,
    is_indoor: 0,
    is_rain_safe: 0,
    is_hidden_gem: 0,
    is_family_friendly: 1,
    low_walking: 0,
    wheelchair_accessible: 0,
    is_active: 1,
    source: 'user_curated_link',
  },
];

async function syncMaharashtra() {
  console.log('[Maharashtra Sync] Initializing database synchronization...');

  for (const exp of MAHARASHTRA_EXPERIENCES) {
    const existing = await dbAll(`SELECT id FROM experiences WHERE id = ?`, [exp.id]);
    if (existing && existing.length > 0) {
      await dbRun(
        `UPDATE experiences SET
          title = ?, tagline = ?, description = ?, category = ?, city = ?, state = ?, area_name = ?,
          price = ?, rating = ?, review_count = ?, approx_duration_mins = ?, image_urls = ?,
          tags = ?, latitude = ?, longitude = ?, is_indoor = ?, is_rain_safe = ?, is_hidden_gem = ?,
          is_family_friendly = ?, low_walking = ?, wheelchair_accessible = ?, source = ?
        WHERE id = ?`,
        [
          exp.title, exp.tagline, exp.description, exp.category, exp.city, exp.state, exp.area_name,
          exp.price, exp.rating, exp.review_count, exp.approx_duration_mins, exp.image_urls,
          exp.tags, exp.latitude, exp.longitude, exp.is_indoor, exp.is_rain_safe, exp.is_hidden_gem,
          exp.is_family_friendly, exp.low_walking, exp.wheelchair_accessible, exp.source, exp.id,
        ]
      );
      console.log(`[Maharashtra Sync] Updated: ${exp.title} (ID ${exp.id})`);
    } else {
      await dbRun(
        `INSERT INTO experiences (
          id, title, tagline, description, category, city, state, area_name,
          price, rating, review_count, approx_duration_mins, image_urls,
          tags, latitude, longitude, is_indoor, is_rain_safe, is_hidden_gem,
          is_family_friendly, low_walking, wheelchair_accessible, is_active, source
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)`,
        [
          exp.id, exp.title, exp.tagline, exp.description, exp.category, exp.city, exp.state, exp.area_name,
          exp.price, exp.rating, exp.review_count, exp.approx_duration_mins, exp.image_urls,
          exp.tags, exp.latitude, exp.longitude, exp.is_indoor, exp.is_rain_safe, exp.is_hidden_gem,
          exp.is_family_friendly, exp.low_walking, exp.wheelchair_accessible, exp.source,
        ]
      );
      console.log(`[Maharashtra Sync] Inserted: ${exp.title} (ID ${exp.id})`);
    }
  }

  // Update experiences_image_map.json
  const mapPath = path.resolve(__dirname, '../../experiences_image_map.json');
  if (fs.existsSync(mapPath)) {
    const mapData = JSON.parse(fs.readFileSync(mapPath, 'utf-8'));
    for (const exp of MAHARASHTRA_EXPERIENCES) {
      const idx = mapData.findIndex((m) => m.id === exp.id);
      const entry = {
        id: exp.id,
        title: exp.title,
        city: exp.city,
        state: exp.state,
        category: exp.category,
        image_url: exp.image_url,
      };
      if (idx >= 0) {
        mapData[idx] = entry;
      } else {
        mapData.push(entry);
      }
    }
    fs.writeFileSync(mapPath, JSON.stringify(mapData, null, 2), 'utf-8');
    console.log('[Maharashtra Sync] Updated experiences_image_map.json with 20 Maharashtra entries');
  }

  console.log('[Maharashtra Sync] Successfully synchronized all 20 Maharashtra destinations across 7 hubs!');
}

syncMaharashtra().catch(console.error);
